const ALL_PLACES=FINAL_PLACES;
if(!ALL_PLACES.some(place=>place.id==='tokyo-daijingu'))ALL_PLACES.push({id:'tokyo-daijingu',name:'東京大神宮',nameJa:'東京大神宮',nameEn:'Tokyo Daijingu',area:'飯田橋',zone:'central',category:'神社寺廟',emoji:'⛩',duration:60,admission:0,cost:0,popularity:94,tags:['御朱印','結緣','東京之伊勢'],desc:'明治時代作為伊勢神宮遙拜殿創建，以結緣信仰與神前結婚式傳統聞名。御朱印通常受理至17:00，活動日以官方公告為準。',lat:35.69995,lng:139.74602,officialUrl:'https://www.tokyodaijingu.or.jp/',sourceUrl:'https://www.tokyodaijingu.or.jp/',completionScore:100,dataTier:'完成度 100%',curated:true,recommendationEligible:true,requiresLiveCheck:true});
const CURATED_PLACES=ALL_PLACES.filter(place=>place.completionScore===100);
const RECOMMENDATION_PLACES=ALL_PLACES.filter(place=>place.recommendationEligible);
const storedSelected=JSON.parse(localStorage.getItem('tabi-selected')||'[]');
const storedVisited=JSON.parse(localStorage.getItem('tabi-visited')||'[]');
const storedVisits=JSON.parse(localStorage.getItem('tabi-visit-records')||'[]');
const storedSeries=JSON.parse(localStorage.getItem('tabi-selected-series')||'[]');
const storedDaySettings=JSON.parse(localStorage.getItem('tabi-day-settings')||'{}');
const storedStopEdits=JSON.parse(localStorage.getItem('tabi-stop-edits')||'{}');
const storedTripDraft=JSON.parse(localStorage.getItem('tabi-trip-draft')||'null');
const storedRequirements=JSON.parse(localStorage.getItem('tabi-normalized-requirements')||'null');
const state={view:'planner',pace:'balanced',party:new Set(['adult']),selected:new Set(storedSelected),selectedSeries:new Set(storedSeries),visited:new Set(storedVisited),visits:storedVisits,itinerary:[],tripDates:[],dayStart:'09:00',dayEnd:'22:00',daySettings:storedDaySettings,stopEdits:storedStopEdits,request:null,activeDay:0,category:'全部',dataQuality:'curated',search:'',visiblePlaces:60,preferences:[],modalPlaceId:null,mapSearch:'',mapFilter:'all',collectionSort:'trip',activeSeriesId:null,normalizedTripRequirements:storedRequirements||TripRequirementsState.create(),manualRequirementFields:new Set()};
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const byId=id=>ALL_PLACES.find(p=>p.id===id);
const featured=['sensoji','tsukiji','shibuya-sky','ameyoko'].map(byId);
const INVALID_RELIGIOUS_TERMS=['教會','教会','教堂','聖堂','大教堂','カトリック','キリスト','Church','Cathedral','chapel','文化財團','文化財団','基金會','基金会','協會','協会','本部','本庁','Residence','樹木','Quercus','車站','駅','站'];
const VALID_TEMPLE_TERMS=['神社','神宮','天満宮','天滿宮','八幡宮','稲荷','稻荷','寺','院','不動尊','観音','觀音','大師','別院','権現','權現'];
function isVerifiedShrinePlace(place){const text=`${place.name||''} ${place.nameJa||''} ${place.nameEn||''} ${place.desc||''}`;return place.category==='神社寺廟'&&Number.isFinite(place.lat)&&Number.isFinite(place.lng)&&!INVALID_RELIGIOUS_TERMS.some(term=>text.toLowerCase().includes(term.toLowerCase()))&&VALID_TEMPLE_TERMS.some(term=>`${place.name||''} ${place.nameJa||''}`.includes(term))}
const SHRINE_PLACES=ALL_PLACES.filter(isVerifiedShrinePlace);
let shrineMap=null,mapMarkers=new Map(),userLocationMarker=null;

const JP_TO_ZH={'稲':'稻','浅':'淺','桜':'櫻','竜':'龍','国':'國','沢':'澤','広':'廣','円':'圓','実':'實','徳':'德','関':'關','応':'應','観':'觀','辺':'邊','弁':'辨','寿':'壽','専':'專','済':'濟','来':'來','亀':'龜','浜':'濱','気':'氣','学':'學','鉄':'鐵','栄':'榮','仏':'佛','当':'當','総':'總','区':'區'};
function traditionalize(value=''){return [...String(value)].map(char=>JP_TO_ZH[char]||char).join('')}
function displayName(place){const primary=/[A-Za-z]{3}/.test(place.name||'')&&place.nameJa?place.nameJa:place.name;return traditionalize(primary||place.nameEn||'名稱待核對')}
function placeKind(place){const text=`${place.nameJa||''} ${place.name||''}`;return /神社|神宮|天満宮|天滿宮|八幡宮|稲荷|稻荷|宮$/.test(text)?'shrine':'temple'}
function persistCollections(){localStorage.setItem('tabi-selected',JSON.stringify([...state.selected]));localStorage.setItem('tabi-selected-series',JSON.stringify([...state.selectedSeries]));localStorage.setItem('tabi-visited',JSON.stringify([...state.visited]));localStorage.setItem('tabi-visit-records',JSON.stringify(state.visits));localStorage.setItem('tabi-day-settings',JSON.stringify(state.daySettings));localStorage.setItem('tabi-stop-edits',JSON.stringify(state.stopEdits))}
function persistTripDraft(){if(!state.itinerary.length)return;localStorage.setItem('tabi-trip-draft',JSON.stringify({itinerary:state.itinerary.map(day=>day.map(place=>place.id)),structuredItinerary:state.structuredItinerary||buildStructuredItinerary(),itineraryValidation:state.itineraryValidation||currentValidation(),tripDates:state.tripDates,dayStart:state.dayStart,dayEnd:state.dayEnd,preferences:state.preferences,normalizedTripRequirements:state.normalizedTripRequirements,savedAt:new Date().toISOString()}))}
function todayLocal(){const now=new Date(),offset=now.getTimezoneOffset()*60000;return new Date(now-offset).toISOString().slice(0,10)}
function addDaysLocal(dateText,days){const date=new Date(`${dateText}T12:00:00`);date.setDate(date.getDate()+days);return date.toISOString().slice(0,10)}
function upsertVisit(id,hasPhoto=false){const place=byId(id);if(!place)return;const tripName=$('#visitTripName')?.value.trim()||'未命名旅程',date=$('#visitDate')?.value||todayLocal(),existing=state.visits.find(item=>item.placeId===id&&item.tripName===tripName);if(existing){existing.date=date;existing.hasPhoto=existing.hasPhoto||hasPhoto}else state.visits.push({id:`${Date.now()}-${id}`,placeId:id,tripName,date,area:place.area,hasPhoto,createdAt:new Date().toISOString()});state.visited.add(id);persistCollections();renderCollectionBook()}
function openPhotoDb(){return new Promise((resolve,reject)=>{const request=indexedDB.open('tabi-goshuin',1);request.onupgradeneeded=()=>request.result.createObjectStore('photos');request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error)})}
async function saveGoshuinPhoto(id,file){const db=await openPhotoDb();await new Promise((resolve,reject)=>{const tx=db.transaction('photos','readwrite');tx.objectStore('photos').put(file,id);tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error)});db.close()}
async function getGoshuinPhoto(id){const db=await openPhotoDb();const photo=await new Promise((resolve,reject)=>{const request=db.transaction('photos').objectStore('photos').get(id);request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error)});db.close();return photo}
async function loadGoshuinPreview(id){const preview=$('#goshuinPreview');preview.classList.add('hidden');preview.removeAttribute('src');try{const photo=await getGoshuinPhoto(id);if(photo){preview.src=URL.createObjectURL(photo);preview.classList.remove('hidden')}}catch{}}

function escapeGuideText(value=''){return String(value).replace(/[&<>"]/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[char]))}
function renderPilgrimageGuides(){
  const seriesGrid=$('#pilgrimageSeriesGrid'),shrineGrid=$('#featuredShrineGrid'),researchGrid=$('#pilgrimageResearchGrid');
  if(!seriesGrid||!shrineGrid||typeof PILGRIMAGE_SERIES==='undefined')return;
  seriesGrid.innerHTML=PILGRIMAGE_SERIES.map(series=>`<button class="pilgrimage-card" data-series="${series.id}"><span class="pilgrimage-icon">${escapeGuideText(series.icon)}</span><small>${escapeGuideText(series.region)}</small><h3>${escapeGuideText(series.title)}</h3><p>${escapeGuideText(series.subtitle)}</p><div><span>${series.stops.length} 站</span><span>${escapeGuideText(series.duration)}</span></div></button>`).join('');
  shrineGrid.innerHTML=FEATURED_SHRINES.map((shrine,index)=>{const fact=SHRINE_FACTS[shrine[1]]||{};return`<article class="featured-shrine-card"><span>${String(index+1).padStart(2,'0')}</span><div><small>${escapeGuideText(shrine[2])} · ${escapeGuideText(shrine[3])}</small><h3>${escapeGuideText(shrine[0])}</h3><p class="detail-alias">${escapeGuideText(shrine[1])}</p><p>${escapeGuideText(shrine[4])}</p><dl class="shrine-fact-list"><div><dt>御祭神／本尊</dt><dd>${escapeGuideText(fact.deity||'待官方核對')}</dd></div><div><dt>社務／授與時間</dt><dd>${escapeGuideText(fact.hours||'待官方核對')}</dd></div><div><dt>地址</dt><dd>${escapeGuideText(fact.address||'待官方核對')}</dd></div><div><dt>主要祈願</dt><dd>${escapeGuideText(fact.prayer||'待官方核對')}</dd></div><div><dt>御朱印</dt><dd>${escapeGuideText(fact.goshuin||'待官方核對')}</dd></div></dl><small class="verified-date">最後核對：${escapeGuideText(fact.checked||'待確認')}</small><a href="${shrine[5]}" target="_blank" rel="noopener">查閱來源 →</a></div></article>`}).join('');
  researchGrid.innerHTML=PILGRIMAGE_RESEARCH_CATALOG.map(item=>`<article><div><small>${escapeGuideText(item[1])} · ${escapeGuideText(item[2])}</small><h3>${escapeGuideText(item[0])}</h3><p>${escapeGuideText(item[3])}</p></div><a href="${item[4]}" target="_blank" rel="noopener">研究來源</a></article>`).join('');
  $$('[data-series]').forEach(button=>button.onclick=()=>openPilgrimageModal(button.dataset.series));
}
function openPilgrimageModal(id){
  const series=PILGRIMAGE_SERIES.find(item=>item.id===id);if(!series)return;
  state.activeSeriesId=id;
  $('#pilgrimageModalMeta').textContent=`${series.region} · ${series.season} · ${series.duration}`;
  $('#pilgrimageModalTitle').textContent=series.title;
  $('#pilgrimageModalHistory').textContent=series.history;
  $('#pilgrimageModalNote').innerHTML=`<p>重要提醒：${escapeGuideText(series.note)}</p>`;
  $('#pilgrimageStopList').innerHTML=series.stops.map((stop,index)=>`<article><b>${index+1}</b><div><small>${escapeGuideText(stop[2])}</small><h3>${escapeGuideText(stop[0])}</h3><p class="detail-alias">${escapeGuideText(stop[1])}</p><p>${escapeGuideText(stop[3])}</p><a href="${stop[4]}" target="_blank" rel="noopener">查看這一站來源</a></div></article>`).join('');
  $('#pilgrimageSourceLink').href=series.sourceUrl;
  $('#addPilgrimageButton').textContent=state.selectedSeries.has(id)?'✓ 已加入整條巡禮':'整條加入行程候選';
  $('#pilgrimageModal').classList.remove('hidden');document.body.style.overflow='hidden';
}
function closePilgrimageModal(){$('#pilgrimageModal').classList.add('hidden');document.body.style.overflow='';state.activeSeriesId=null}
function findPlaceForStop(stop){const names=[stop[0],stop[1]].filter(Boolean);return SHRINE_PLACES.find(place=>names.some(name=>`${place.name} ${place.nameJa}`.includes(name)||name.includes(place.nameJa||'__')))}
function togglePilgrimageSeries(id){const series=PILGRIMAGE_SERIES.find(item=>item.id===id);if(!series)return;const matches=series.stops.map(findPlaceForStop).filter(Boolean);if(state.selectedSeries.has(id)){state.selectedSeries.delete(id);matches.forEach(place=>state.selected.delete(place.id))}else{state.selectedSeries.add(id);matches.forEach(place=>state.selected.add(place.id))}persistCollections();renderCandidates();openPilgrimageModal(id)}

function aliases(place){return [place.nameJa,place.nameEn].filter(Boolean).join(' · ')}
function placeCard(place,featuredMode=false){const selected=state.selected.has(place.id),metric=`完成度 ${place.completionScore}%${place.recommendationEligible?' · 可排行程':' · 待動態核對'}`;return `<article class="place-card ${featuredMode?'featured':''}" data-id="${place.id}" tabindex="0" aria-label="查看 ${place.name} 詳細介紹"><div class="place-art art-${place.zone}"><span>${place.emoji}</span><button class="save-place ${selected?'saved':''}" aria-label="${selected?'移除':'加入'} ${place.name}">${selected?'✓':'＋'}</button><small>${place.area}</small></div><div class="place-info"><div class="place-meta"><span>${place.category}</span><b>${metric}</b></div><h3>${place.name}</h3><small class="place-alias">${aliases(place)}</small><p>${place.desc}</p><div class="tag-row">${place.tags.slice(0,3).map(t=>`<span>${t}</span>`).join('')}</div></div></article>`}
function renderFeatured(){$('#featuredGrid').innerHTML=featured.map(p=>placeCard(p,true)).join('');bindPlaceCards()}
function renderFilters(){const cats=['全部',...new Set(ALL_PLACES.map(p=>p.category))];$('#categoryFilters').innerHTML=cats.map((c,i)=>`<button class="filter-chip ${i===0?'active':''}" data-category="${c}">${c}</button>`).join('');$$('.filter-chip').forEach(b=>b.onclick=()=>{$$('.filter-chip').forEach(x=>x.classList.remove('active'));b.classList.add('active');state.category=b.dataset.category;state.visiblePlaces=60;renderPlaces()})}
function passesQuality(place){if(state.dataQuality==='curated')return place.completionScore===100;if(state.dataQuality==='usable')return place.completionScore>=80;return place.completionScore<80}
function filteredPlaces(){const q=state.search.trim().toLowerCase();return ALL_PLACES.filter(p=>passesQuality(p)&&(state.category==='全部'||p.category===state.category)&&(!q||`${p.name} ${p.nameJa} ${p.nameEn} ${p.area} ${p.category} ${p.cuisine||''} ${p.tags.join(' ')}`.toLowerCase().includes(q))).sort((a,b)=>(Number(b.curated)-Number(a.curated))||(b.popularity-a.popularity))}
function renderPlaces(){const list=filteredPlaces(),visible=list.slice(0,state.visiblePlaces),label=state.dataQuality==='curated'?'完成度 100%':state.dataQuality==='usable'?'完成度至少 80%':'低於 80%';$('#placesGrid').innerHTML=visible.map(p=>placeCard(p)).join('');$('#placeCount').textContent=`${label}：${list.length.toLocaleString()} 個地點`;$('#loadMoreButton').classList.toggle('hidden',visible.length>=list.length);bindPlaceCards()}
function toggleCandidate(id){state.selected.has(id)?state.selected.delete(id):state.selected.add(id);persistCollections();renderCandidates();renderFeatured();renderPlaces()}
function bindPlaceCards(){$$('.save-place').forEach(btn=>btn.onclick=e=>{e.stopPropagation();toggleCandidate(btn.closest('.place-card').dataset.id)});$$('.place-card').forEach(card=>{card.onclick=()=>openPlaceModal(card.dataset.id);card.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();openPlaceModal(card.dataset.id)}}})}
function renderCandidates(){const box=$('#candidateList');if(!box)return;const places=[...state.selected].map(byId).filter(Boolean);box.innerHTML=places.length?`<h3>已加入 ${places.length} 個候選地點</h3>${places.map(place=>`<button data-candidate="${place.id}"><span>${place.category==='神社寺廟'?(placeKind(place)==='shrine'?'⛩':'卍'):place.emoji}</span><b>${escapeGuideText(displayName(place))}</b><small>${escapeGuideText(place.area)}</small></button>`).join('')}<p>產生行程時會優先保留這些地點；資料已儲存在本機。</p>`:'';$$('[data-candidate]').forEach(button=>button.onclick=()=>openPlaceModal(button.dataset.candidate))}
function renderCollectionBook(){const box=$('#collectionBook');if(!box)return;const records=[...state.visits].sort((a,b)=>a.date.localeCompare(b.date)||a.createdAt.localeCompare(b.createdAt));if(!records.length){box.innerHTML='<p class="collection-empty">尚無參拜紀錄。到寺社詳情上傳御朱印或勾選已參拜，就會加入這裡。</p>';return}const keyOf=item=>state.collectionSort==='area'?(item.area||'未分類'):state.collectionSort==='date'?'參拜時間軸':(item.tripName||'未命名旅程'),groups=Object.groupBy?Object.groupBy(records,keyOf):records.reduce((result,item)=>{const key=keyOf(item);(result[key]||(result[key]=[])).push(item);return result},{});box.innerHTML=Object.entries(groups).map(([key,items])=>`<section><h3>${escapeGuideText(key)} <small>${items.length} 間</small></h3><div>${items.map(item=>{const place=byId(item.placeId);return place?`<button data-collection-place="${place.id}"><span>${item.hasPhoto?'📷':'✓'}</span><b>${escapeGuideText(displayName(place))}</b><small>${escapeGuideText(item.date)} · ${escapeGuideText(place.area)}</small></button>`:''}).join('')}</div></section>`).join('');$$('[data-collection-place]').forEach(button=>button.onclick=()=>openPlaceModal(button.dataset.collectionPlace))}
$$('[data-collection-sort]').forEach(button=>button.onclick=()=>{$$('[data-collection-sort]').forEach(item=>item.classList.remove('active'));button.classList.add('active');state.collectionSort=button.dataset.collectionSort;renderCollectionBook()});
$$('#qualitySelector button').forEach(button=>button.onclick=()=>{$$('#qualitySelector button').forEach(item=>item.classList.remove('active'));button.classList.add('active');state.dataQuality=button.dataset.quality;state.visiblePlaces=60;renderPlaces()});

function openPlaceModal(id){const place=byId(id);if(!place)return;state.modalPlaceId=id;$('#modalPlaceTier').textContent=state.visited.has(id)?'✓ 已參拜':(place.dataTier||'待稽核');$('#modalPlaceName').textContent=displayName(place);$('#modalPlaceAliases').textContent=aliases(place);$('#modalPlaceIntro').textContent=place.desc;const price=place.priceBand||(place.curated?(place.admission?`門票參考 ¥${place.admission.toLocaleString()}`:'免費或無門票'):'尚未人工確認');const shrineFact=SHRINE_FACTS[place.nameJa]||SHRINE_FACTS[place.name]||{};const facts=[['區域',place.area],['分類',place.category],['主題／類型',place.cuisine||place.tags[0]||'待確認'],['建議停留',place.curated?`約 ${place.duration} 分鐘`:'尚未人工確認'],['費用／價位',price],['營業／授與時間',shrineFact.hours||place.openingHours||'請查官方最新資訊'],...(place.branchUniqueness?[['這間分店的差異',place.branchUniqueness]]:[]),...(place.travelerReason?[['適合什麼旅客',place.travelerReason]]:[])];$('#modalPlaceFacts').innerHTML=facts.map(([key,value])=>`<div><dt>${key}</dt><dd>${value}</dd></div>`).join('');const warnings=[...(place.qualityReasons||[]),...(place.queueRisk?[`候位風險：${place.queueRisk}`]:[]),...(place.reservationNote?[place.reservationNote]:[])];$('#modalPlaceWarnings').innerHTML=warnings.slice(0,5).map(reason=>`<p>⚠ ${reason}</p>`).join('');const source=place.officialUrl||place.sourceUrl||`https://www.google.com/maps/search/?api=1&query=${place.lat},${place.lng}`;$('#modalSourceLink').href=source;const isTemple=place.category==='神社寺廟'&&isVerifiedShrinePlace(place);$('#modalMapButton').classList.toggle('hidden',!isTemple);$('#visitRecorder').classList.toggle('hidden',!isTemple);$('#visitDate').value=$('#visitDate').value||todayLocal();$('#visitedButton').textContent=state.visited.has(id)?'✓ 已參拜（點擊取消）':'✓ 標示為已參拜';loadGoshuinPreview(id);$('#modalSaveButton').textContent=state.selected.has(id)?'從行程候選移除':'加入行程候選';$('#placeModal').classList.remove('hidden');document.body.style.overflow='hidden'}
function closePlaceModal(){$('#placeModal').classList.add('hidden');document.body.style.overflow='';state.modalPlaceId=null}
$('#closePlaceModal').onclick=closePlaceModal;$('[data-close-modal]').onclick=closePlaceModal;$('#modalSaveButton').onclick=()=>{const id=state.modalPlaceId;if(!id)return;toggleCandidate(id);openPlaceModal(id)};document.addEventListener('keydown',event=>{if(event.key==='Escape'&&!$('#placeModal').classList.contains('hidden'))closePlaceModal()});
$('#modalMapButton').onclick=()=>{const id=state.modalPlaceId;closePlaceModal();showPlaceOnMap(id)};
$('#visitedButton').onclick=()=>{const id=state.modalPlaceId;if(!id)return;if(state.visited.has(id)){state.visited.delete(id);state.visits=state.visits.filter(item=>item.placeId!==id);persistCollections();renderCollectionBook()}else upsertVisit(id);refreshMapMarkers();openPlaceModal(id)};
$('#goshuinCamera').onchange=async event=>{const id=state.modalPlaceId,file=event.target.files?.[0];if(!id||!file)return;await saveGoshuinPhoto(id,file);upsertVisit(id,true);refreshMapMarkers();await loadGoshuinPreview(id);$('#visitedButton').textContent='✓ 已參拜（點擊取消）';event.target.value=''};

function switchView(view){state.view=view;$$('.view').forEach(v=>v.classList.remove('active'));$(`#${view}View`).classList.add('active');$$('.nav-link').forEach(b=>b.classList.toggle('active',b.dataset.view===view));if(view==='map')requestAnimationFrame(()=>{initShrineMap();shrineMap?.invalidateSize()});window.scrollTo({top:0,behavior:'smooth'})}
$$('[data-view]').forEach(b=>b.addEventListener('click',()=>switchView(b.dataset.view)));
function requirementsFormSnapshot(){return{dates:{start:$('#tripStartDate').value,end:$('#tripEndDate').value},startTime:$('#dayStartTime').value,endTime:$('#dayEndTime').value,budget:Number($('#budget').value),pace:{leisurely:'LEISURELY',balanced:'BALANCED',intensive:'INTENSIVE'}[state.pace],party:[...state.party]}}
function saveNormalizedRequirements(){localStorage.setItem('tabi-normalized-requirements',JSON.stringify(state.normalizedTripRequirements))}
function syncFormFromRequirements(){const fields=state.normalizedTripRequirements.fields,pace={LEISURELY:'leisurely',BALANCED:'balanced',INTENSIVE:'intensive'}[fields.pace?.value];if(pace&&!state.manualRequirementFields.has('pace')){$$('#paceSelector button').forEach(button=>button.classList.toggle('selected',button.dataset.value===pace));state.pace=pace}if(!state.manualRequirementFields.has('startTime')&&fields.startTime?.value)$('#dayStartTime').value=fields.startTime.value;if(!state.manualRequirementFields.has('endTime')&&fields.endTime?.value)$('#dayEndTime').value=fields.endTime.value;if(!state.manualRequirementFields.has('budget')&&fields.budget?.value)$('#budget').value=String(fields.budget.value);if(!state.manualRequirementFields.has('party')&&fields.party?.value?.length){state.party=new Set(fields.party.value);$$('#partySelector button').forEach(button=>button.classList.toggle('selected',state.party.has(button.dataset.value)))}}
function updateRequirementFromForm(field){state.manualRequirementFields.add(field);state.normalizedTripRequirements=TripRequirementsState.merge({base:state.normalizedTripRequirements,rawText:$('#tripPrompt').value,form:requirementsFormSnapshot(),manualFields:[...state.manualRequirementFields]});saveNormalizedRequirements()}
$$('#paceSelector button').forEach(b=>b.onclick=()=>{$$('#paceSelector button').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');state.pace=b.dataset.value;updateRequirementFromForm('pace')});
$$('#partySelector button').forEach(b=>b.onclick=()=>{const v=b.dataset.value;if(v==='adult'){state.party=new Set(['adult']);$$('#partySelector button').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');updateRequirementFromForm('party');return}state.party.delete('adult');$('#partySelector [data-value="adult"]').classList.remove('selected');state.party.has(v)?state.party.delete(v):state.party.add(v);b.classList.toggle('selected');if(!state.party.size){state.party.add('adult');$('#partySelector [data-value="adult"]').classList.add('selected')}updateRequirementFromForm('party')});

const THEME_WORDS={
  food:['美食','吃','壽司','拉麵','燒肉','甜點','市場','居酒屋'],shopping:['購物','逛街','血拼','免稅','藥妝','百貨','outlet','伴手禮'],
  shrine:['神社','寺廟','御守','鳥居','文化','古蹟'],anime:['動漫','動畫','寶可夢','任天堂','鋼彈','扭蛋','電器'],
  nature:['自然','公園','花','櫻','海景','富士山'],night:['夜景','展望台','夜生活','酒吧','夜店','泡泡浴'],family:['小孩','親子','迪士尼','樂園'],classic:['第一次','初訪','經典','地標','必去']
};
const THEME_CATEGORIES={food:['美食市場','特色餐廳'],shopping:['購物血拼'],shrine:['神社寺廟','歷史文化'],anime:['動漫娛樂'],nature:['公園自然'],night:['展望夜景'],family:['主題樂園','動漫娛樂'],classic:['城市地標','神社寺廟','歷史文化','展望夜景']};
const FOOD_TERMS=['壽司','迴轉壽司','北海道海鮮','江戶前','燒肉','壽喜燒','涮涮鍋','火鍋','鍋物','居酒屋','拉麵','沾麵','擔擔麵','燒鳥','串燒','螃蟹','帝王蟹','河豚','和牛','牛舌','天婦羅','天丼','豬排','鰻魚','蕎麥麵','文字燒','洋食','咖哩','海鮮','創意料理','法國料理','甜點','咖啡'];
const NEARBY_ZONES=['chiba','kamakura','yokohama','hakone','fuji','nikko','kawagoe','karuizawa'];
const CITY_ZONES=['asakusa','ueno','central','shibuya','shinjuku','minato','bay','ikebukuro','west','east'];
const ZONE_KEYWORDS={chiba:['迪士尼','舞濱','千葉','成田'],kamakura:['鎌倉','江之島','江島'],yokohama:['橫濱'],hakone:['箱根'],fuji:['富士山','河口湖','忍野','御殿場'],nikko:['日光'],kawagoe:['川越'],karuizawa:['輕井澤'],asakusa:['淺草','晴空塔'],ueno:['上野','阿美橫','秋葉原','湯島'],central:['築地','銀座','東京站','皇居','日本橋','八重洲'],shibuya:['澀谷','原宿','明治神宮','青山'],shinjuku:['新宿'],minato:['東京鐵塔','六本木','麻布台','麻布'],bay:['豐洲','台場','門前仲町'],ikebukuro:['池袋','大塚'],west:['吉祥寺','下北澤','豪德寺','中野','池上','戶越'],east:['柴又','帝釋天']};

function includesAny(text,words){return words.some(w=>text.toLowerCase().includes(w.toLowerCase()))}
function parseClockFromText(text){let start=$('#dayStartTime').value||'09:00',end=$('#dayEndTime').value||'22:00';if(/睡到中午|中午才出門|下午才出門/.test(text))start='12:00';const startMatch=text.match(/(?:早上|上午|中午|下午|晚上)?\s*(\d{1,2})(?:[:：](\d{2}))?\s*點?(?:開始|出門|起床)/);if(startMatch){let hour=Number(startMatch[1]);if(/下午|晚上/.test(startMatch[0])&&hour<12)hour+=12;start=`${String(hour).padStart(2,'0')}:${startMatch[2]||'00'}`}if(/半夜|凌晨才回|玩到半夜/.test(text))end='00:30';const endMatch=text.match(/(?:晚上|半夜|凌晨)?\s*(\d{1,2})(?:[:：](\d{2}))?\s*點?(?:回飯店|結束|收工)/);if(endMatch){let hour=Number(endMatch[1]);if(/晚上/.test(endMatch[0])&&hour<12)hour+=12;end=`${String(hour).padStart(2,'0')}:${endMatch[2]||'00'}`}return{start,end}}
function parseRequest(text){const negative={food:['不想吃','不要美食','不想一直吃','不要一直吃','不以美食為主'],shopping:['不想購物','不要購物','不血拼','不買東西'],shrine:['不想逛寺社','不要寺社','神社寺廟都不要'],anime:['不看動漫','不喜歡動漫'],nature:['不想看自然'],night:['不看夜景','不要夜生活'],family:['不要樂園']};const themes=Object.entries(THEME_WORDS).filter(([key,words])=>includesAny(text,words)&&!includesAny(text,negative[key]||[])).map(([key])=>key);if(!themes.length)themes.push('food','shopping','shrine');const excludedThemes=Object.entries(negative).filter(([,words])=>includesAny(text,words)).map(([key])=>key),mentionedZones=Object.entries(ZONE_KEYWORDS).filter(([,words])=>includesAny(text,words)).map(([zone])=>zone),musts=ALL_PLACES.filter(p=>includesAny(text,[p.name,...p.name.split('・'),p.nameJa,p.nameEn])).map(p=>p.id),foodTerms=FOOD_TERMS.filter(term=>includesAny(text,[term])),clock=parseClockFromText(text),unsupported=[];if(/泡泡浴|風俗|成人娛樂/.test(text))unsupported.push('成人娛樂店目前沒有經人工驗證的安全資料，僅改以夜間活動偏好處理，不會捏造店家');const templeOnly=/只(?:想|要)?去寺廟|只排寺廟|寺廟限定|佛寺限定|只(?:想|要)?去寺院/.test(text),shrineOnly=/只(?:想|要)?去神社|只排神社|神社限定/.test(text),numberMap={一:1,二:2,三:3,四:4,五:5,六:6,七:7,八:8,九:9,十:10},foodDayMatch=text.match(/(?:要吃|吃)([一二三四五六七八九十\d]+)天/);return{themes,excludedThemes,mentionedZones,musts,foodTerms,clock,unsupported,singleMeal:/一頓|一餐|只吃一(?:間|家)/.test(text),religiousMode:templeOnly?'temple_only':shrineOnly?'shrine_only':'both',dayQuotas:{food:foodDayMatch?(Number(foodDayMatch[1])||numberMap[foodDayMatch[1]]||0):0,amusement:/一天(?:去|玩)?(?:遊樂園|樂園|迪士尼)/.test(text)?1:0,night:/一天(?:晚上)?(?:看|去)?夜景/.test(text)?1:0}}}
function allowedByRequest(place,request){if(request.religiousMode==='temple_only')return place.category==='神社寺廟'&&placeKind(place)==='temple';if(request.religiousMode==='shrine_only')return place.category==='神社寺廟'&&placeKind(place)==='shrine';return true}
async function smartParseRequest(text){
  const base=String(window.TABI_CONFIG?.smartApiBaseUrl||'').replace(/\/$/,'');
  const form=TripRequirementsState.plain(state.normalizedTripRequirements);
  const placeCatalog=RECOMMENDATION_PLACES.slice().sort((a,b)=>Number(b.popularity||0)-Number(a.popularity||0)).slice(0,220).map(place=>({id:place.id,name:place.name,nameJa:place.nameJa||'',nameEn:place.nameEn||'',aliases:(place.aliases||[]).slice(0,6),category:place.category,zone:place.zone}));
  const result=await RequirementPipeline.parse({
    text,
    form,
    allowFallback:false,
    aiParser:async payload=>{
      if(!base)throw new Error('AI_GATEWAY_NOT_CONFIGURED');
      let lastError;
      for(let attempt=1;attempt<=2;attempt++){
        const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),25000);
        try{
          const response=await fetch(`${base}/api/plan/requirements`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({...payload,placeCatalog}),signal:controller.signal});
          if(!response.ok){
            const detail=await response.text().catch(()=> '');
            const error=new Error(`HTTP ${response.status}${detail?`: ${detail.slice(0,180)}`:''}`);
            error.retryable=response.status===429||response.status>=500;
            throw error;
          }
          return response.json();
        }catch(error){
          lastError=error;
          const retryable=error?.name==='AbortError'||error?.retryable!==false;
          if(attempt===2||!retryable)break;
        }finally{clearTimeout(timer)}
      }
      throw new Error(lastError?.name==='AbortError'?'AI_REQUEST_TIMEOUT':(lastError?.message||'AI_REQUEST_FAILED'));
    },
    // 舊 parser 僅保留給明確啟用的離線 fallback；正式規劃不會走到這裡。
    fallbackParser:async()=>parseRequest(text)
  });
  if(!result.ok)return{aiUnavailable:true,parserMode:result.mode,parserErrors:result.errors,parserSource:`AI unavailable (${result.mode})`};
  const requirements=result.requirements;
  return{
    aiUnavailable:false,
    parserMode:'AI',
    travelRequirements:requirements,
    aiRequirements:requirements,
    aiMeta:result.meta,
    parserSource:'AI 需求理解完成',
    themes:requirements.interests||[],
    excludedThemes:requirements.avoidances||[],
    mentionedZones:[],
    musts:[],
    foodTerms:requirements.foodPreferences||[],
    clock:{start:form.startTime||'09:00',end:form.endTime||'22:00'},
    unsupported:requirements.warnings||[],
    religiousMode:'both',
    dayQuotas:{food:0,amusement:0,night:0}
  };
}
async function applyAiItineraryCandidate(request,dates){const base=String(window.TABI_CONFIG?.smartApiBaseUrl||'').replace(/\/$/,'');if(!base)return{ok:false,error:'AI_GATEWAY_NOT_CONFIGURED',attempts:0};const pool=[...new Map(state.itinerary.flat().concat(RECOMMENDATION_PLACES.filter(place=>request.musts.includes(place.id)||state.selected.has(place.id))).map(place=>[place.id,place])).values()].slice(0,100),candidates=pool.map(place=>({id:place.id,name:displayName(place),category:place.category,zone:place.zone,duration:place.duration,openingHours:place.openingHours||'',tags:(place.tags||[]).slice(0,8)})),payload={requirements:request.aiRequirements||request.travelRequirements||{},dates,startTime:state.dayStart,endTime:state.dayEnd,candidates};let lastError;for(let attempt=1;attempt<=2;attempt++){try{const response=await fetch(`${base}/api/plan/generate`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(payload)});if(!response.ok)throw new Error(`HTTP ${response.status}`);const result=await response.json(),candidate=result.itineraryCandidate;if(!candidate||candidate.tripDays!==dates.length||candidate.days?.length!==dates.length)throw new Error('AI_DAY_COUNT_MISMATCH');const ordered=candidate.days.slice().sort((a,b)=>a.dayNumber-b.dayNumber);if(ordered.some((day,index)=>day.dayNumber!==index+1))throw new Error('AI_NON_SEQUENTIAL_DAYS');const mapped=ordered.map(day=>(day.placeIds||[]).map(id=>byId(id)).filter(Boolean));if(mapped.some(day=>day.length<2))throw new Error('AI_EMPTY_OR_THIN_DAY');state.itinerary=mapped;request.aiPlanMeta={...result.meta,attempts:attempt};request.parserSource=`${request.parserSource}；AI 候選行程：${result.meta?.model||'model 未回傳'}`;return{ok:true,attempts:attempt}}catch(error){lastError=error}}request.aiPlanMeta={attempts:2,error:lastError?.message||'UNKNOWN'};return{ok:false,error:lastError?.message||'UNKNOWN',attempts:2}}
function scorePlace(place,request){if(place.category==='神社寺廟'&&!isVerifiedShrinePlace(place))return-10000;let score=place.popularity;for(const theme of request.themes)if((THEME_CATEGORIES[theme]||[]).includes(place.category)||place.tags.some(t=>THEME_WORDS[theme]?.some(w=>t.includes(w))))score+=220;for(const theme of request.excludedThemes)if((THEME_CATEGORIES[theme]||[]).includes(place.category))score-=1000;const foodText=`${place.name} ${place.nameJa} ${place.cuisine||''} ${place.tags.join(' ')}`;if(request.foodTerms.some(term=>foodText.includes(term)))score+=300;if(request.musts.includes(place.id))score+=2000;if(state.selected.has(place.id))score+=1200;if((state.party.has('elderly')||state.party.has('stroller'))&&['整日','階梯'].some(t=>place.tags.includes(t)))score-=180;return score}
function rankZones(zones,request){return zones.map(zone=>{const ps=RECOMMENDATION_PLACES.filter(p=>p.zone===zone).sort((a,b)=>scorePlace(b,request)-scorePlace(a,request));return{zone,score:(request.mentionedZones.includes(zone)?500:0)+(ps.slice(0,3).reduce((s,p)=>s+scorePlace(p,request),0)/3||0)}}).sort((a,b)=>b.score-a.score).map(x=>x.zone)}
const JAPAN_HOLIDAYS={'2026-01-01':'元日','2026-01-12':'成人之日','2026-02-11':'建國紀念日','2026-02-23':'天皇誕生日','2026-03-20':'春分日','2026-04-29':'昭和之日','2026-05-03':'憲法紀念日','2026-05-04':'綠之日','2026-05-05':'兒童節','2026-05-06':'補假','2026-07-20':'海之日','2026-08-11':'山之日','2026-09-21':'敬老之日','2026-09-22':'國民休日','2026-09-23':'秋分日','2026-10-12':'運動之日','2026-11-03':'文化之日','2026-11-23':'勤勞感謝日','2027-01-01':'元日','2027-01-11':'成人之日','2027-02-11':'建國紀念日','2027-02-23':'天皇誕生日','2027-03-21':'春分日','2027-03-22':'補假','2027-04-29':'昭和之日','2027-05-03':'憲法紀念日','2027-05-04':'綠之日','2027-05-05':'兒童節','2027-07-19':'海之日','2027-08-11':'山之日','2027-09-20':'敬老之日','2027-09-23':'秋分日','2027-10-11':'運動之日','2027-11-03':'文化之日','2027-11-23':'勤勞感謝日'};
function dateRange(start,end){const result=[],from=new Date(`${start}T12:00:00`),to=new Date(`${end}T12:00:00`);if(!start||!end||from>to)return result;for(let date=from;date<=to&&result.length<31;date.setDate(date.getDate()+1))result.push(date.toISOString().slice(0,10));return result}
function crowdInfo(date){const holiday=JAPAN_HOLIDAYS[date],monthDay=date.slice(5),weekend=[0,6].includes(new Date(`${date}T12:00:00`).getDay()),golden=monthDay>='04-29'&&monthDay<='05-06',newYear=monthDay<='01-03',obon=monthDay>='08-11'&&monthDay<='08-16';return{level:golden||newYear?'極高':holiday||obon?'高':weekend?'中高':'一般',reason:golden?'黃金週':newYear?'日本新年':holiday||obon|| (weekend?'週末':''),holiday}}
function updateHolidayNotice(){const dates=dateRange($('#tripStartDate').value,$('#tripEndDate').value),risks=dates.map(date=>({date,...crowdInfo(date)})).filter(item=>item.reason);$('#holidayNotice').innerHTML=risks.length?`⚠ 本次包含 ${risks.map(item=>`${item.date.slice(5)} ${item.holiday||item.reason}`).join('、')}；熱門寺社、樂園與商圈將提高候位與移動緩衝。`:`✓ ${dates.length||0} 天行程未撞上已公布國定假日；週末仍會另行加上人潮緩衝。`;return dates}
function isFoodPlace(place){return ['美食市場','特色餐廳'].includes(place.category)}
function balanceDayCandidates(candidates,count,request){
  const explicitFood=request.themes.includes('food'),maxFood=request.singleMeal?1:(explicitFood?2:1),foods=candidates.filter(isFoodPlace).slice(0,maxFood),nightPlaces=candidates.filter(place=>place.category==='展望夜景').slice(0,1),nonFoods=candidates.filter(place=>!isFoodPlace(place)&&place.category!=='展望夜景').slice(0,Math.max(0,count-foods.length-nightPlaces.length));
  const result=[...nonFoods];
  foods.forEach((food,index)=>result.splice(Math.min(result.length,index===0?2:Math.max(3,result.length)),0,food));
  result.push(...nightPlaces);
  return result.slice(0,count).filter((place,index,array)=>index===0||!isFoodPlace(place)||!isFoodPlace(array[index-1]));
}
function structuredItem(place,previous=null){const leg=previous?estimateTransportLeg(previous,place):{mode:'起點',minutes:0,fare:0},seriesTitles=typeof PILGRIMAGE_SERIES==='undefined'?[]:PILGRIMAGE_SERIES.filter(series=>series.stops.some(stop=>findPlaceForStop(stop)?.id===place.id)).map(series=>series.title);return{placeId:place.id,name:displayName(place),category:place.category,tags:[...(place.tags||[]),...seriesTitles],collectionSeries:seriesTitles[0]||place.series||null,estimatedDuration:Number(place.duration)||60,openingHoursStatus:place.category==='神社寺廟'?(serviceTimeKnown(place)?'VERIFIED_REFERENCE':'REQUIRES_LIVE_CHECK'):'REQUIRES_LIVE_CHECK',travelFromPrevious:{mode:leg.mode,minutes:leg.minutes,fare:leg.fare||0}}}
function buildStructuredItinerary(){return{tripDays:state.tripDates.length,days:state.tripDates.map((date,index)=>{const items=state.itinerary[index]||[],setting=state.daySettings[date]||{start:state.dayStart,end:state.dayEnd};return{dayNumber:index+1,date,title:dayAreaLabel(items)||`Day ${index+1}`,dayType:'full',items:items.map((place,itemIndex)=>structuredItem(place,items[itemIndex-1])),startTime:setting.start,endTime:setting.end}})}}
function currentValidation(){const plan=buildStructuredItinerary(),validation=ItineraryCore.validateItinerary(plan);state.structuredItinerary=plan;state.itineraryValidation=validation;return validation}
function candidatesForZone(zone,request,used,count,anchor=null){const candidates=RECOMMENDATION_PLACES.filter(place=>place.zone===zone&&!used.has(place.id)&&allowedByRequest(place,request)&&(place.category!=='神社寺廟'||isVerifiedShrinePlace(place))).sort((a,b)=>(scorePlace(b,request)-(anchor?distance(anchor,b)*35:0))-(scorePlace(a,request)-(anchor?distance(anchor,a)*35:0)));return balanceDayCandidates(candidates,count,request)}
function feasibleDayItems(day,dayIndex){const setting=daySetting(dayIndex),start=clockMinutes(setting.start),end=clockMinutes(setting.end)+(clockMinutes(setting.end)<=start?1440:0),result=[];let time=start,meals=0;for(const place of day){if(isFoodPlace(place)){const target=meals===0?11*60+30:17*60+30;if(time<target)time=target;meals++}const stay=Number(place.duration||60)+(state.party.has('elderly')?15:0);if(time+stay>end)break;result.push(place);time+=stay;const next=day[result.length];if(next)time+=estimateTransportLeg(place,next).minutes+10}return result}
function normalizeItineraryToSchedule(){state.itinerary=state.itinerary.map((day,index)=>feasibleDayItems((day||[]).filter(Boolean),index))}
function repairIncompleteItinerary(request,chosen,minimumStops,desired){const used=new Set(state.itinerary.flat().filter(Boolean).map(place=>place.id)),rankedZones=rankZones([...CITY_ZONES,...NEARBY_ZONES],request);for(let index=0;index<state.tripDates.length;index++){let day=Array.isArray(state.itinerary[index])?state.itinerary[index].filter(Boolean):[];if(day.length>=2){state.itinerary[index]=day;continue}const preferred=day[0]?.zone||chosen[index],zoneOrder=[preferred,...rankedZones].filter((zone,pos,array)=>zone&&array.indexOf(zone)===pos),needed=Math.max(2,Math.min(desired,4));for(const zone of zoneOrder){const additions=candidatesForZone(zone,request,used,needed-day.length);if(day.length&&zone!==day[0].zone)continue;if(additions.length){day=[...day,...additions];additions.forEach(place=>used.add(place.id))}if(day.length>=2)break}state.itinerary[index]=day}return currentValidation()}
function repairDayAtIndex(dayIndex,request=state.request,preferredPlace=null){
  if(!Number.isInteger(dayIndex)||dayIndex<0||dayIndex>=state.tripDates.length)return{success:false,error:'INVALID_DAY'};
  const original=state.itinerary.map(day=>[...(day||[])]),used=new Set(original.flat().filter(Boolean).filter(place=>!original[dayIndex].includes(place)).map(place=>place.id));
  const existing=original[dayIndex].filter(Boolean),ranked=rankZones([...CITY_ZONES,...NEARBY_ZONES],request),represented=new Set(original.filter((_,index)=>index!==dayIndex).flat().map(place=>place.zone));
  const preferredZone=preferredPlace?.zone||existing[0]?.zone,zoneOrder=[preferredZone,...ranked.filter(zone=>!represented.has(zone)),...ranked].filter((zone,index,array)=>zone&&array.indexOf(zone)===index);
  let replacement=[];
  for(const zone of zoneOrder){
    const seed=preferredPlace&&preferredPlace.zone===zone?[preferredPlace]:existing.filter(place=>place.zone===zone);
    seed.forEach(place=>used.add(place.id));
    const desired=Math.max(3,Math.min(5,Math.floor((clockMinutes(daySetting(dayIndex).end)-clockMinutes(daySetting(dayIndex).start)+1440)%1440/120)||4));
    const additions=candidatesForZone(zone,request,used,Math.max(0,desired-seed.length),seed[0]||null);
    replacement=balanceDayCandidates([...seed,...additions],Math.max(2,desired),request);
    if(replacement.length>=2)break;
  }
  state.itinerary[dayIndex]=feasibleDayItems(replacement,dayIndex);
  const validation=currentValidation();
  if(!validation.valid){state.itinerary=original;currentValidation();return{success:false,error:'VALIDATION_FAILED',validation}}
  return{success:true,dayIndex,day:replacement,validation};
}
function showPlannerValidationError(validation){const box=$('#plannerValidationError'),errors=validation.errors||[],days=[...new Set(errors.filter(error=>error.dayNumber).map(error=>`第 ${error.dayNumber} 天`))],messages={DAY_COUNT_MISMATCH:'旅行天數沒有完整產生',EMPTY_DAY:'這一天還沒有可用行程',THIN_FULL_DAY:'這一天的內容不足以成為完整行程',DAILY_ACTIVITY_CAP:'這一天安排得太滿',MAIN_ATTRACTION_CAP:'主要景點過多',LATE_END:'結束時間超出設定',WALKING_CAP:'預估步行量過高',CLOSED_PLACE:'有地點在抵達時未營業',CATEGORY_REPETITION:'同類型地點過度集中',RELIGIOUS_RATIO:'寺社比例超出你的偏好',AI_REQUIREMENT_PARSER_UNAVAILABLE:'AI 需求理解目前忙碌，無法可靠規劃',AI_PLANNER_UNAVAILABLE:'AI 規劃服務目前忙碌，無法保證行程品質'};const readable=errors.map(error=>messages[error.code]||(/^REQUIREMENT_/.test(error.code||'')?'有一項必去需求尚未確認':'這次規劃尚未通過完整性檢查'));box.innerHTML=`<b>${days.join('、')||'行程'}尚未成功產生</b><p>${[...new Set(readable)].map(escapeGuideText).join('；')}。你的需求與表單仍會保留。</p><button type="button" id="retryMissingDays">再試一次</button><button type="button" id="reportPlannerProblem">回報問題</button>`;box.classList.remove('hidden');$('#retryMissingDays').onclick=()=>generateItinerary();$('#reportPlannerProblem').onclick=()=>{box.querySelector('p').textContent='謝謝你的回報。請保留目前畫面，稍後可將截圖提供給開發者；你的需求沒有被清除。'}}
function clearPlannerValidationError(){$('#plannerValidationError')?.classList.add('hidden')}
function applyTravelRequirements(request){const requirements=request.travelRequirements;if(!requirements)return;for(const constraint of requirements.dayConstraints||[]){const indexes=constraint.dayNumber==='EVERY'?state.tripDates.map((_,index)=>index):[constraint.dayNumber==='LAST'?state.tripDates.length-1:Number(constraint.dayNumber)-1];for(const dayIndex of indexes){if(dayIndex<0||dayIndex>=state.tripDates.length)continue;if(constraint.type==='EARLIEST_START')state.daySettings[state.tripDates[dayIndex]]={...daySetting(dayIndex),start:constraint.value};if(constraint.type==='LATEST_END')state.daySettings[state.tripDates[dayIndex]]={...daySetting(dayIndex),end:constraint.value};if(constraint.type==='PRIMARY_INTEREST'&&constraint.value==='購物'){const preferred=RECOMMENDATION_PLACES.filter(place=>place.category==='購物血拼').sort((a,b)=>scorePlace(b,{...request,themes:['shopping']})-scorePlace(a,{...request,themes:['shopping']}))[0];if(preferred)repairDayAtIndex(dayIndex,{...request,themes:['shopping']},preferred)}}}}
function applyRequirementTargetsToRequest(request){for(const constraint of request.travelRequirements?.dayConstraints||[]){if(constraint.type!=='REQUIRED_DESTINATION')continue;const place=ALL_PLACES.find(item=>`${item.name}${item.nameJa||''}${item.nameEn||''}`.includes(constraint.value));if(place)request.musts=[...new Set([...(request.musts||[]),place.id])]}return request}
function enforceStructuredRequirements(request){
  const requirements=request.travelRequirements;if(!requirements)return;
  const reserved=new Set(),find=value=>RECOMMENDATION_PLACES.find(place=>`${place.name}${place.nameJa||''}${place.nameEn||''}${place.cuisine||''}${(place.tags||[]).join('')}`.includes(value));
  const removeElsewhere=place=>state.itinerary.forEach(day=>{const index=day.findIndex(item=>item.id===place.id);if(index>=0)day.splice(index,1)});
  const focusDay=(place,dayIndex,{fullDay=false,companion=null}={})=>{if(!place||dayIndex<0||dayIndex>=state.itinerary.length)return false;removeElsewhere(place);const extras=fullDay?[]:RECOMMENDATION_PLACES.filter(item=>item.zone===place.zone&&item.id!==place.id&&!isFoodPlace(item)&&allowedByRequest(item,request)&&(item.category!=='神社寺廟'||isVerifiedShrinePlace(item))).sort((a,b)=>scorePlace(b,request)-scorePlace(a,request)).slice(0,companion?0:3);state.itinerary[dayIndex]=[place,...(companion?[companion]:extras)];reserved.add(dayIndex);return true};
  const addMeal=(place,dayIndex)=>{if(!place)return false;removeElsewhere(place);const day=state.itinerary[dayIndex],sameZone=day.length&&day.every(item=>item.zone===place.zone);if(!sameZone){const extras=RECOMMENDATION_PLACES.filter(item=>item.zone===place.zone&&!isFoodPlace(item)&&item.id!==place.id&&allowedByRequest(item,request)&&(item.category!=='神社寺廟'||isVerifiedShrinePlace(item))).sort((a,b)=>scorePlace(b,request)-scorePlace(a,request)).slice(0,3);state.itinerary[dayIndex]=[place,...extras]}else state.itinerary[dayIndex]=[...day.filter(item=>!isFoodPlace(item)),place];return true};
  const targets=(requirements.dayConstraints||[]).filter(item=>item.type==='REQUIRED_DESTINATION'),fixed=targets.filter(item=>Number.isInteger(item.dayNumber)),flex=targets.filter(item=>item.dayNumber==='FLEX');
  fixed.forEach(item=>{const dayIndex=item.dayNumber-1;focusDay(find(item.value),dayIndex,{fullDay:/迪士尼/.test(item.value)})});
  const flexIndexes=state.itinerary.map((_,index)=>index).filter(index=>!reserved.has(index));
  flex.forEach((item,index)=>{const dayIndex=flexIndexes[index]??flexIndexes.at(-1),companion=item.value==='河口湖'?find('忍野八海'):null;focusDay(find(item.value),dayIndex,{companion})});
  const nonMealDays=new Set(fixed.map(item=>item.dayNumber-1));flex.forEach((item,index)=>{if(item.value==='河口湖')nonMealDays.add(flexIndexes[index]??flexIndexes.at(-1))});const mealDays=state.itinerary.map((_,index)=>index).filter(index=>!nonMealDays.has(index));
  const allocatedMealDays=new Set();for(const frequency of requirements.frequencyRequirements||[]){const choices=RECOMMENDATION_PLACES.filter(place=>`${place.name}${place.nameJa||''}${place.nameEn||''}${place.cuisine||''}${(place.tags||[]).join('')}`.includes(frequency.category));let placed=0;for(const dayIndex of mealDays){if(placed>=frequency.days)break;if(allocatedMealDays.has(dayIndex))continue;if(state.itinerary[dayIndex].some(place=>`${place.name}${place.cuisine||''}${(place.tags||[]).join('')}`.includes(frequency.category))){placed++;allocatedMealDays.add(dayIndex);continue}const zone=state.itinerary[dayIndex][0]?.zone,choice=choices.find(place=>place.zone===zone&&!state.itinerary.flat().some(item=>item.id===place.id))||choices.find(place=>!state.itinerary.flat().some(item=>item.id===place.id));if(choice&&addMeal(choice,dayIndex)){placed++;allocatedMealDays.add(dayIndex)}}}
}
// Requirement entity resolution belongs to PlannerEngine. Do not remap AI output
// through the legacy keyword parser on the successful AI path.
async function generateItinerary(){
  const text=$('#tripPrompt').value,request=await smartParseRequest(text),dates=updateHolidayNotice();if(!dates.length){$('#holidayNotice').textContent='⚠ 回程日期不可早於出發日期，且目前一次最多規劃31天。';return}state.preferences=request.themes;state.request=request;state.tripDates=dates;state.dayStart=request.clock.start;state.dayEnd=request.clock.end;$('#dayStartTime').value=state.dayStart;$('#dayEndTime').value=state.dayEnd;const days=dates.length,available=Math.max(240,clockMinutes(state.dayEnd)-clockMinutes(state.dayStart)+(clockMinutes(state.dayEnd)<=clockMinutes(state.dayStart)?1440:0));
  const minimumStops=available>=480?4:available>=330?3:2;
  let desired=Math.max(minimumStops,Math.min(8,Math.floor(available/(state.pace==='intensive'?95:state.pace==='leisurely'?155:120))));if(state.pace==='leisurely'&&(state.party.has('elderly')||state.party.has('child')||state.party.has('stroller')))desired=Math.max(minimumStops,desired-1);
  const requestedNearby=rankZones(NEARBY_ZONES.filter(z=>request.mentionedZones.includes(z)),request).slice(0,Math.max(0,days-2));
  const cityDays=days-requestedNearby.length,cityOrder=rankZones(CITY_ZONES,request),mustZones=[...new Set(ALL_PLACES.filter(p=>request.musts.includes(p.id)||state.selected.has(p.id)).map(p=>p.zone).filter(z=>CITY_ZONES.includes(z)))];
  const chosenCity=[...new Set([...mustZones,...cityOrder])].slice(0,cityDays),chosen=[...chosenCity,...requestedNearby];while(chosen.length<days){const fallback=[...cityOrder,...rankZones(NEARBY_ZONES,request)].find(zone=>!chosen.includes(zone));if(!fallback)break;chosen.push(fallback)}
  const used=new Set();state.itinerary=chosen.map((zone,index)=>{const risk=crowdInfo(dates[index]);let candidates=RECOMMENDATION_PLACES.filter(p=>p.zone===zone&&allowedByRequest(p,request)&&(p.category!=='神社寺廟'||isVerifiedShrinePlace(p))).sort((a,b)=>scorePlace(b,request)-scorePlace(a,request)).filter(p=>!used.has(p.id));if(request.themes.length){const relevant=candidates.filter(place=>request.themes.some(theme=>(THEME_CATEGORIES[theme]||[]).includes(place.category))),other=candidates.filter(place=>!relevant.includes(place));candidates=[...relevant,...other]}const count=Math.max(minimumStops,NEARBY_ZONES.includes(zone)?Math.min(4,desired):desired-(risk.level==='極高'?1:0)),balanced=balanceDayCandidates(candidates,count,request);balanced.forEach(p=>used.add(p.id));return balanced});
  state.itinerary.forEach((day,dayIndex)=>{if(day.length>=minimumStops)return;const targetZone=day[0]?.zone||chosen[dayIndex],fillers=RECOMMENDATION_PLACES.filter(place=>place.zone===targetZone&&!used.has(place.id)&&allowedByRequest(place,request)&&(place.category!=='神社寺廟'||isVerifiedShrinePlace(place))).sort((a,b)=>scorePlace(b,request)-scorePlace(a,request));for(const place of fillers){if(day.length>=minimumStops)break;if(isFoodPlace(place)&&day.some(isFoodPlace))continue;day.push(place);used.add(place.id)}});
  const selectedMissing=[...state.selected].map(byId).filter(place=>place&&!used.has(place.id)&&allowedByRequest(place,request));selectedMissing.forEach(place=>{const eligible=state.itinerary.filter(day=>day.some(item=>item.zone===place.zone));if(!eligible.length)return;const target=eligible.reduce((best,day)=>{const load=day.length+(isFoodPlace(place)?day.filter(isFoodPlace).length*4:0),bestLoad=best.length+(isFoodPlace(place)?best.filter(isFoodPlace).length*4:0);return load<bestLoad?day:best},eligible[0]);if(target&&!target.some(item=>item.id===place.id))target.unshift(place)});state.itinerary=state.itinerary.map(day=>{const ordered=day.sort((a,b)=>{const aClose=serviceDeadline(a),bClose=serviceDeadline(b);return aClose-bClose||scorePlace(b,request)-scorePlace(a,request)});return balanceDayCandidates(ordered,ordered.length,request)});const aiCandidate=await applyAiItineraryCandidate(request,dates);if(!aiCandidate.ok){request.unsupported.push(`AI 候選行程連續 ${aiCandidate.attempts} 次失敗：${aiCandidate.error}`);showPlannerValidationError({errors:[{code:'AI_PLANNER_UNAVAILABLE',message:'AI 服務暫時失敗，無法保證行程品質，請稍後重試。已保留需求，不會顯示規則補位行程。'}]});state.itinerary=[];return false}
  const seniorMode=Boolean(request.travelRequirements?.mobilityProfile?.seniorPresent||request.travelRequirements?.specialNeeds?.includes('SENIOR_FRIENDLY')||state.party.has('elderly'));dates.forEach(date=>{state.daySettings[date]={start:seniorMode&&state.dayStart<'09:00'?'09:00':state.dayStart,end:seniorMode&&state.dayEnd>'20:30'?'20:30':state.dayEnd}});applyTravelRequirements(request);enforceStructuredRequirements(request);normalizeItineraryToSchedule();let validation=currentValidation();for(let attempt=0;!validation.valid&&attempt<2;attempt++){validation=repairIncompleteItinerary(request,chosen,minimumStops,desired);applyTravelRequirements(request);enforceStructuredRequirements(request);normalizeItineraryToSchedule();validation=currentValidation()}if(!validation.valid){showPlannerValidationError(validation);return false}if(seniorMode){const seniorValidation=ItineraryCore.validateSeniorTravel(state.structuredItinerary,{religiousPrimary:request.travelRequirements?.religiousSitePreference?.primaryInterest,dailyWalkingKm:state.itinerary.map(day=>dayMetrics(day).walk)});state.seniorTravelValidation=seniorValidation;if(!seniorValidation.valid){showPlannerValidationError(seniorValidation);return false}}if(request.travelRequirements){state.requirementTraceability=TravelQuality.buildTraceability(request.travelRequirements,state.structuredItinerary);state.travelQualityEvaluation=TravelQuality.evaluateItinerary(state.structuredItinerary,request.travelRequirements);if(state.travelQualityEvaluation.criticalFailures.length){const unsatisfied=state.requirementTraceability.filter(item=>item.status!=='SATISFIED').map(item=>`${item.requirement}（${item.evidence.join('、')}）`);showPlannerValidationError({errors:[...state.travelQualityEvaluation.criticalFailures.map(code=>({code,message:`品質評估未通過：${code}`})),...unsatisfied.map(message=>({code:'UNSATISFIED_REQUIREMENT',message}))]});return false}}clearPlannerValidationError();persistCollections();persistTripDraft();state.activeDay=0;renderTrip();return true;
}
async function generateItineraryV2(){
  const dates=updateHolidayNotice(),request=state.request||await smartParseRequest($('#tripPrompt').value);
  if(!dates.length){$('#holidayNotice').textContent='⚠ 回程日期不可早於出發日期，且目前一次最多規劃31天。';return false}
  if(request.aiUnavailable||request.parserMode!=='AI'){
    showPlannerValidationError({errors:[{code:'AI_REQUIREMENT_PARSER_UNAVAILABLE',message:'AI 需求理解目前無法使用；系統不會靜默改用關鍵字規則產生正式行程。請稍後重試。'}]});
    return false;
  }
  const normalized=TripRequirementsState.plain(state.normalizedTripRequirements),requirements={...request.travelRequirements,pace:normalized.pace||request.travelRequirements.pace,budget:normalized.budget||request.travelRequirements.budget,dailyStartTime:normalized.startTime||'09:00',dailyEndTime:normalized.endTime||'22:00'};
  request.travelRequirements=requirements;
  state.tripDates=dates;
  state.request=request;
  const result=PlannerEngine.run({requirements,places:RECOMMENDATION_PLACES,dates});
  state.plannerEngineResult=result;
  state.requirementTraceability=result.traceability;
  state.seniorTravelValidation={valid:!result.validation.errors.some(error=>String(error.code).includes('SENIOR')),errors:result.validation.errors};
  if(!result.ok){
    const traceErrors=result.traceability.filter(item=>item.priority==='MUST'&&item.status!=='SATISFIED').map(item=>({code:`REQUIREMENT_${item.status}`,message:`${item.value}：${item.evidence.join('、')}`}));
    showPlannerValidationError({errors:[...result.validation.errors.map(error=>({...error,message:error.message||error.code})),...traceErrors]});
    state.itinerary=[];
    return false;
  }
  state.daySettings={};
  state.itinerary=result.itinerary.days.map(day=>{
    state.daySettings[day.date]={start:day.startTime,end:day.endTime};
    return day.items.map(item=>byId(item.placeId)).filter(Boolean);
  });
  state.dayStart=result.itinerary.days[0]?.startTime||'09:00';
  state.dayEnd=result.policy.latestEndTime;
  state.structuredItinerary=result.itinerary;
  state.itineraryValidation=result.validation;
  clearPlannerValidationError();
  persistCollections();persistTripDraft();state.activeDay=0;renderTrip();
  return true;
}

// The old generator remains in source temporarily for rollback and comparison,
// but production calls this separated Planner Engine path.
generateItinerary=generateItineraryV2;

function timeAdd(time,min){let[h,m]=time.split(':').map(Number),total=h*60+m+min;return`${String(Math.floor(total/60)).padStart(2,'0')}:${String(total%60).padStart(2,'0')}`}
function clockMinutes(time){const[h,m]=time.split(':').map(Number);return h*60+m}
function serviceDeadline(place){if(place.category!=='神社寺廟')return 24*60;const fact=SHRINE_FACTS[place.nameJa]||SHRINE_FACTS[place.name]||{},matches=(fact.hours||place.openingHours||'').matchAll(/(\d{1,2}):?(\d{2})/g),times=[...matches].map(match=>Number(match[1])*60+Number(match[2]));return times.length?Math.max(...times):17*60}
function serviceTimeKnown(place){const fact=SHRINE_FACTS[place.nameJa]||SHRINE_FACTS[place.name];return Boolean(fact&&/\d{1,2}:?\d{2}/.test(fact.hours||''))}
function distance(a,b){if(!a||!b)return 0;const r=6371,dLat=(b.lat-a.lat)*Math.PI/180,dLon=(b.lng-a.lng)*Math.PI/180,x=Math.sin(dLat/2)**2+Math.cos(a.lat*Math.PI/180)*Math.cos(b.lat*Math.PI/180)*Math.sin(dLon/2)**2;return r*2*Math.atan2(Math.sqrt(x),Math.sqrt(1-x))}
function mealBudget(){const budget=Number($('#budget').value);return budget<=6000?2500:budget<=10000?4000:budget<=16000?6000:8000}
function dayMetrics(day){let walk=0,transitMinutes=0,localFare=0;day.forEach((p,i)=>{if(i){const leg=estimateTransportLeg(day[i-1],p);walk+=leg.mode==='步行'?leg.km:Math.min(leg.km,.45);transitMinutes+=leg.minutes;localFare+=leg.fare}});const admission=day.reduce((s,p)=>s+(p.admission||0),0),nearTransit=Math.max(0,...day.map(p=>p.transit||0)),transport=nearTransit||localFare,meals=mealBudget();return{walk:walk+day.length*.35,transitMinutes,admission,transport,meals,cost:admission+transport+meals,transportBasis:nearTransit?'近郊人工參考值':'東京 Metro IC 票價級距估算'}}
function dayAreaLabel(day){const areas=[...new Set(day.map(p=>p.area))];return areas.length<=2?areas.join('・'):`${areas[0]}等區域`}
function daySetting(index=state.activeDay){const date=state.tripDates[index];return state.daySettings[date]||{start:state.dayStart,end:state.dayEnd}}
function stopEditKey(date,id){return`${date}::${id}`}
function stopEdit(date,id){return state.stopEdits[stopEditKey(date,id)]||{}}
function moveStop(from,to){const day=state.itinerary[state.activeDay];if(!day||to<0||to>=day.length||from===to)return;const[item]=day.splice(from,1);day.splice(to,0,item);persistTripDraft();renderTrip()}
function removeStop(index){state.itinerary[state.activeDay]?.splice(index,1);persistTripDraft();renderTrip()}
function addStopToActiveDay(id){const place=byId(id),day=state.itinerary[state.activeDay];if(!place||!day||day.some(item=>item.id===id))return;day.push(place);state.selected.add(id);persistCollections();persistTripDraft();renderTrip()}
function renderTrip(){const days=state.itinerary.length,all=state.itinerary.flat(),metrics=state.itinerary.map(dayMetrics),themeNames={food:'美食',shopping:'購物',shrine:'神社寺廟',anime:'動漫',nature:'自然',night:'夜間活動',family:'親子',classic:'初訪經典'};$('#resultDays').textContent=days;$('#totalStops').textContent=all.length;$('#totalCost').textContent='¥'+metrics.reduce((s,m)=>s+m.cost,0).toLocaleString();$('#totalWalk').textContent=metrics.reduce((s,m)=>s+m.walk,0).toFixed(1)+' km';const warnings=state.request?.unsupported?.length?` · ⚠ ${state.request.unsupported.join('；')}`:'';$('#resultSummary').textContent=`${state.tripDates[0]}～${state.tripDates.at(-1)} · 每日 ${state.dayStart}～${state.dayEnd} · 偏好：${state.preferences.map(x=>themeNames[x]).join('、')}${warnings}`;$('#dayTabs').innerHTML=state.itinerary.map((d,i)=>{const risk=crowdInfo(state.tripDates[i]);return`<button class="day-tab ${i===state.activeDay?'active':''}" data-day="${i}"><b>${state.tripDates[i]} · DAY ${i+1}</b><span>${dayAreaLabel(d)}</span><small>${d.length} 個地點 · 人潮 ${risk.level}${risk.reason?`（${risk.holiday||risk.reason}）`:''}</small></button>`}).join('');$$('.day-tab').forEach(b=>b.onclick=()=>{state.activeDay=Number(b.dataset.day);renderDay()});$('#emptyTrip').classList.add('hidden');$('#tripResult').classList.remove('hidden');renderDay();switchView('trip')}
function renderDay(){
  const day=state.itinerary[state.activeDay]||[],metrics=dayMetrics(day),date=state.tripDates[state.activeDay],crowd=crowdInfo(date),setting=daySetting();
  $$('.day-tab').forEach((b,i)=>b.classList.toggle('active',i===state.activeDay));$('#dayArea').textContent=dayAreaLabel(day)||'東京';$('#dayTitle').textContent=`${date} · 第 ${state.activeDay+1} 天`;$('#activeDayStart').value=setting.start;$('#activeDayEnd').value=setting.end;
  const available=RECOMMENDATION_PLACES.filter(place=>!day.some(item=>item.id===place.id)).sort((a,b)=>b.popularity-a.popularity).slice(0,250);$('#tripAddPlace').innerHTML='<option value="">搜尋／選擇景點…</option>'+available.map(place=>`<option value="${place.id}">${escapeGuideText(displayName(place))}｜${escapeGuideText(place.area)}｜${escapeGuideText(place.category)}</option>`).join('');
  let time=setting.start,startMinutes=clockMinutes(time),endMinutes=clockMinutes(setting.end)+(clockMinutes(setting.end)<=startMinutes?1440:0),mealCount=0;const startTime=time,stopHtml=[];
  for(let i=0;i<day.length;i++){
    const p=day[i],edit=stopEdit(date,p.id);if(edit.arrival)time=edit.arrival;
    if(isFoodPlace(p)&&!edit.arrival){const target=mealCount===0?11*60+30:17*60+30,current=clockMinutes(time)+(clockMinutes(time)<startMinutes?1440:0);if(current<target)time=`${String(Math.floor(target/60)%24).padStart(2,'0')}:${String(target%60).padStart(2,'0')}`;mealCount++}
    const arrival=time,arrivalMinutes=clockMinutes(arrival)+(clockMinutes(arrival)<startMinutes?1440:0),deadline=serviceDeadline(p),knownService=serviceTimeKnown(p),stay=p.duration+(state.party.has('elderly')?15:0)+(crowd.level==='極高'?20:crowd.level==='高'?10:0),deadlineText=`${String(Math.floor(deadline/60)).padStart(2,'0')}:${String(deadline%60).padStart(2,'0')}`,serviceRisk=p.category==='神社寺廟'?(!knownService?'⚠ 尚未取得官方授與時間，暫以 17:00 保守估算；出發前必須再查官網':arrivalMinutes>deadline-30?`⚠ 官方參考授與時間約 ${deadlineText} 截止，這個抵達時間有風險`:`✓ 已按官方參考授與截止 ${deadlineText} 排序`):'';
    if(arrivalMinutes+stay>endMinutes)break;time=timeAdd(time,stay);let leg='';if(i<day.length-1){const estimate=estimateTransportLeg(p,day[i+1]);leg=`<div class="travel-leg"><span>↓</span> ${estimate.mode}約 ${estimate.minutes} 分鐘${estimate.fare?` · IC 票價級距約 ¥${estimate.fare}`:''} · API 即時路線待後端安全代理啟用</div>`;time=timeAdd(time,estimate.minutes+10)}const feeText=p.priceBand?`價位 ${p.priceBand}`:(p.admission?'門票參考 ¥'+p.admission.toLocaleString():'免費或無門票');
    stopHtml.push(`<article class="timeline-stop editable-stop" draggable="true" data-stop-index="${i}"><time><input class="stop-arrival" data-stop-id="${p.id}" type="time" value="${arrival}" aria-label="${escapeGuideText(displayName(p))}抵達時間"></time><div class="stop-marker">${i+1}</div><div class="stop-card"><div class="stop-main"><span class="stop-category">${p.category}${isFoodPlace(p)?(mealCount===1?' · 午餐':' · 晚餐'):''}</span><h3>${p.emoji} ${escapeGuideText(displayName(p))}</h3><small class="place-alias">${aliases(p)}</small><p>${p.desc}</p>${serviceRisk?`<p class="service-risk">${serviceRisk}</p>`:''}<label class="stop-note-label">本站筆記<textarea class="stop-note" data-stop-id="${p.id}" placeholder="必逛、必吃、必買、必拍，或記錄預約資訊…">${escapeGuideText(edit.note||'')}</textarea></label></div><div class="stop-detail"><span>停留約 ${Math.round(stay/10)*10} 分鐘</span><span>${feeText}</span><div class="stop-edit-actions"><button data-move="up" data-index="${i}" aria-label="上移">↑</button><button data-move="down" data-index="${i}" aria-label="下移">↓</button><button data-remove-stop="${i}" aria-label="刪除">刪除</button></div><button class="show-stop-detail" data-id="${p.id}">查看完整介紹</button></div></div>${leg}</article>`)
  }
  const schedule=`<div class="schedule-banner"><div><b>今日 Schedule｜${startTime}–${time}</b><span>${stopHtml.length} 站 · 本日最晚 ${setting.end} · 人潮 ${crowd.level}</span></div><div><b>${crowd.reason?'人潮提醒':'日期檢查完成'}</b><span>${crowd.holiday||crowd.reason||'非國定假日；週末仍依日期調整'}</span></div></div>`;$('#timeline').innerHTML=schedule+stopHtml.join('')+`<div class="day-total"><b>今日基本旅費</b><span>餐食預算 ¥${metrics.meals.toLocaleString()}</span><span>交通暫估 ¥${metrics.transport.toLocaleString()}</span><span>門票 ¥${metrics.admission.toLocaleString()}</span><strong>合計 ¥${metrics.cost.toLocaleString()}</strong><small>${metrics.transportBasis}；不含住宿、機票與個人購物。<a href="${TRANSPORT_REFERENCE.tokyoMetro.sourceUrl}" target="_blank" rel="noopener">官方票價依據</a></small></div>`;const activeTab=$$('.day-tab')[state.activeDay]?.querySelector('small');if(activeTab)activeTab.textContent=`${stopHtml.length} 個可完成地點 · 人潮 ${crowd.level}${crowd.reason?`（${crowd.holiday||crowd.reason}）`:''}`;
  $$('.show-stop-detail').forEach(button=>button.onclick=()=>openPlaceModal(button.dataset.id));$$('[data-move]').forEach(button=>button.onclick=()=>moveStop(Number(button.dataset.index),Number(button.dataset.index)+(button.dataset.move==='up'?-1:1)));$$('[data-remove-stop]').forEach(button=>button.onclick=()=>removeStop(Number(button.dataset.removeStop)));$$('.stop-arrival').forEach(input=>input.onchange=()=>{const key=stopEditKey(date,input.dataset.stopId);state.stopEdits[key]={...state.stopEdits[key],arrival:input.value};persistCollections();renderDay()});$$('.stop-note').forEach(input=>input.oninput=()=>{const key=stopEditKey(date,input.dataset.stopId);state.stopEdits[key]={...state.stopEdits[key],note:input.value};persistCollections()});let dragged=null;$$('.editable-stop').forEach(card=>{card.ondragstart=()=>dragged=Number(card.dataset.stopIndex);card.ondragover=event=>event.preventDefault();card.ondrop=event=>{event.preventDefault();moveStop(dragged,Number(card.dataset.stopIndex))}})
}

$('#plannerForm').addEventListener('submit',e=>{e.preventDefault();startCompanionPlanning()});
$('#tripStartDate').addEventListener('change',()=>{updateHolidayNotice();updateRequirementFromForm('dates')});$('#tripEndDate').addEventListener('change',()=>{updateHolidayNotice();updateRequirementFromForm('dates')});$('#dayStartTime').addEventListener('change',()=>updateRequirementFromForm('startTime'));$('#dayEndTime').addEventListener('change',()=>updateRequirementFromForm('endTime'));$('#budget').addEventListener('change',()=>updateRequirementFromForm('budget'));
$('#activeDayStart').addEventListener('change',event=>{const date=state.tripDates[state.activeDay];state.daySettings[date]={...daySetting(),start:event.target.value};persistCollections();persistTripDraft();renderDay()});
$('#activeDayEnd').addEventListener('change',event=>{const date=state.tripDates[state.activeDay];state.daySettings[date]={...daySetting(),end:event.target.value};persistCollections();persistTripDraft();renderDay()});
$('#tripAddPlaceButton').onclick=()=>addStopToActiveDay($('#tripAddPlace').value);
$('#saveTripButton').onclick=()=>{persistCollections();persistTripDraft();const button=$('#saveTripButton');button.textContent='✓ 已儲存在本機';setTimeout(()=>button.textContent='儲存行程',1600)};
$('#regenerateButton').onclick=()=>{state.activeDay=0;switchView('planner')};
$('#placeSearch').addEventListener('input',event=>{state.search=event.target.value;state.visiblePlaces=60;renderPlaces()});
$('#loadMoreButton').onclick=()=>{state.visiblePlaces+=60;renderPlaces()};

function escapeMapText(value=''){return String(value).replace(/[&<>'"]/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[char]))}
function mapFilteredPlaces(){const q=state.mapSearch.trim().toLowerCase(),tripIds=new Set(state.itinerary.flat().map(place=>place.id));return SHRINE_PLACES.filter(place=>{const matchesSearch=!q||`${place.name} ${place.nameJa||''} ${place.nameEn||''} ${place.area} ${(place.tags||[]).join(' ')}`.toLowerCase().includes(q);const matchesState=state.mapFilter==='all'||(state.mapFilter==='visited'&&state.visited.has(place.id))||(state.mapFilter==='unvisited'&&!state.visited.has(place.id))||(state.mapFilter==='trip'&&tripIds.has(place.id));return matchesSearch&&matchesState}).sort((a,b)=>(Number(b.completionScore)-Number(a.completionScore))||(b.popularity-a.popularity))}
function markerPopup(place){const visited=state.visited.has(place.id);return `<div class="map-popup"><b>${visited?'✓ ':''}${escapeMapText(displayName(place))}</b><small>${escapeMapText(place.nameJa||place.nameEn||'')}</small><span>${escapeMapText(place.area)} · ${placeKind(place)==='shrine'?'神社':'寺院'}${visited?' · 已參拜':''}</span><button data-map-detail="${escapeMapText(place.id)}">查看／記錄御朱印</button></div>`}
function renderMapList(){const places=mapFilteredPlaces();$('#mapPlaceTotal').textContent=SHRINE_PLACES.length.toLocaleString();$('#mapResultCount').textContent=`${places.length.toLocaleString()} 間已驗證寺社`;$('#mapPlaceList').innerHTML=places.slice(0,200).map(place=>`<button class="map-place-item ${state.visited.has(place.id)?'visited':''}" data-map-place="${place.id}"><span>${placeKind(place)==='shrine'?'⛩':'卍'}</span><div><b>${escapeMapText(displayName(place))}</b><small>${escapeMapText(place.area)} · ${placeKind(place)==='shrine'?'神社':'寺院'}${state.visited.has(place.id)?' · 已參拜':''}</small></div><em>${state.visited.has(place.id)?'✓':'資料 '+place.completionScore+'%'}</em></button>`).join('')||'<p class="map-empty">找不到符合條件的寺社。</p>';$$('[data-map-place]').forEach(button=>button.onclick=()=>focusMapPlace(button.dataset.mapPlace))}
function renderMapMarkers(){if(!shrineMap)return;const visibleIds=new Set(mapFilteredPlaces().map(place=>place.id));for(const [id,marker] of mapMarkers){if(visibleIds.has(id)){if(!shrineMap.hasLayer(marker))marker.addTo(shrineMap)}else if(shrineMap.hasLayer(marker))marker.removeFrom(shrineMap)}renderMapList()}
function templeMarkerIcon(place){const shrine=placeKind(place)==='shrine',visited=state.visited.has(place.id);return L.divIcon({className:'temple-marker-wrap',html:`<div class="temple-marker ${shrine?'shrine':'temple'} ${visited?'visited':''}"><span>${visited?'✓':(shrine?'⛩':'卍')}</span></div>`,iconSize:[38,44],iconAnchor:[19,42],popupAnchor:[0,-38]})}
function initShrineMap(){if(shrineMap||typeof L==='undefined')return;shrineMap=L.map('shrineMap',{zoomControl:true,minZoom:5}).setView([35.6812,139.7671],10);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'&copy; OpenStreetMap contributors'}).addTo(shrineMap);SHRINE_PLACES.forEach(place=>{const marker=L.marker([place.lat,place.lng],{title:displayName(place),icon:templeMarkerIcon(place)}).bindPopup(markerPopup(place));marker.on('popupopen',()=>setTimeout(()=>{$$('[data-map-detail]').forEach(button=>button.onclick=()=>openPlaceModal(button.dataset.mapDetail))},0));mapMarkers.set(place.id,marker);marker.addTo(shrineMap)});renderMapList();fitAllShrines()}
function refreshMapMarkers(){for(const place of SHRINE_PLACES){const marker=mapMarkers.get(place.id);if(marker){marker.setIcon(templeMarkerIcon(place));marker.setPopupContent(markerPopup(place))}}if(shrineMap)renderMapList()}
function focusMapPlace(id){initShrineMap();const place=byId(id),marker=mapMarkers.get(id);if(!place||!marker)return;shrineMap.setView([place.lat,place.lng],16,{animate:true});marker.openPopup()}
function showPlaceOnMap(id){switchView('map');requestAnimationFrame(()=>focusMapPlace(id))}
function fitAllShrines(){initShrineMap();const visible=mapFilteredPlaces().map(place=>[place.lat,place.lng]);if(visible.length)shrineMap.fitBounds(visible,{padding:[24,24],maxZoom:12})}
$('#mapSearch').addEventListener('input',event=>{state.mapSearch=event.target.value;renderMapMarkers()});
$$('[data-map-filter]').forEach(button=>button.onclick=()=>{$$('[data-map-filter]').forEach(item=>item.classList.remove('active'));button.classList.add('active');state.mapFilter=button.dataset.mapFilter;renderMapMarkers();fitAllShrines()});
$('#fitMapButton').onclick=fitAllShrines;
$('#locateMeButton').onclick=()=>{if(!navigator.geolocation){alert('此裝置不支援定位。');return}navigator.geolocation.getCurrentPosition(position=>{initShrineMap();const latlng=[position.coords.latitude,position.coords.longitude];if(userLocationMarker)userLocationMarker.remove();userLocationMarker=L.circleMarker(latlng,{radius:9,color:'#174c3d',fillColor:'#d8ef9c',fillOpacity:1}).addTo(shrineMap).bindPopup('你目前的位置').openPopup();shrineMap.setView(latlng,14)},()=>alert('無法取得位置，請在 iPhone 瀏覽器允許定位權限。'),{enableHighAccuracy:true,timeout:10000})};
$('#closePilgrimageModal').onclick=closePilgrimageModal;
$('[data-close-pilgrimage]').onclick=closePilgrimageModal;
$('#addPilgrimageButton').onclick=()=>{if(state.activeSeriesId)togglePilgrimageSeries(state.activeSeriesId)};
document.addEventListener('keydown',event=>{if(event.key==='Escape'&&!$('#pilgrimageModal').classList.contains('hidden'))closePilgrimageModal()});
const initialDate=todayLocal(),savedUnified=storedTripDraft?.normalizedTripRequirements||storedRequirements;$('#tripStartDate').value=savedUnified?.fields?.dates?.value?.start||initialDate;$('#tripEndDate').value=savedUnified?.fields?.dates?.value?.end||addDaysLocal(initialDate,5);if(savedUnified){state.normalizedTripRequirements=savedUnified;syncFormFromRequirements()}if(storedTripDraft?.itinerary?.length){state.itinerary=storedTripDraft.itinerary.map(day=>day.map(byId).filter(Boolean));state.tripDates=storedTripDraft.tripDates||[];state.dayStart=storedTripDraft.dayStart||'09:00';state.dayEnd=storedTripDraft.dayEnd||'22:00';state.preferences=storedTripDraft.preferences||[];state.request={unsupported:[],normalizedTripRequirements:TripRequirementsState.plain(state.normalizedTripRequirements)}}renderFeatured();renderFilters();renderPlaces();renderPilgrimageGuides();renderCandidates();renderCollectionBook();updateHolidayNotice();if(state.itinerary.length){renderTrip();switchView('planner')}
