const ALL_PLACES=FINAL_PLACES;
const CURATED_PLACES=ALL_PLACES.filter(place=>place.completionScore===100);
const RECOMMENDATION_PLACES=ALL_PLACES.filter(place=>place.recommendationEligible);
const state={view:'planner',pace:'balanced',party:new Set(['adult']),selected:new Set(),itinerary:[],activeDay:0,category:'全部',dataQuality:'curated',search:'',visiblePlaces:60,preferences:[],modalPlaceId:null,mapSearch:''};
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const byId=id=>ALL_PLACES.find(p=>p.id===id);
const featured=['sensoji','tsukiji','shibuya-sky','ameyoko'].map(byId);
const SHRINE_PLACES=ALL_PLACES.filter(place=>place.category==='神社寺廟'&&Number.isFinite(place.lat)&&Number.isFinite(place.lng));
let shrineMap=null,mapMarkers=new Map(),userLocationMarker=null;

function escapeGuideText(value=''){return String(value).replace(/[&<>"]/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[char]))}
function renderPilgrimageGuides(){
  const seriesGrid=$('#pilgrimageSeriesGrid'),shrineGrid=$('#featuredShrineGrid'),researchGrid=$('#pilgrimageResearchGrid');
  if(!seriesGrid||!shrineGrid||typeof PILGRIMAGE_SERIES==='undefined')return;
  seriesGrid.innerHTML=PILGRIMAGE_SERIES.map(series=>`<button class="pilgrimage-card" data-series="${series.id}"><span class="pilgrimage-icon">${escapeGuideText(series.icon)}</span><small>${escapeGuideText(series.region)}</small><h3>${escapeGuideText(series.title)}</h3><p>${escapeGuideText(series.subtitle)}</p><div><span>${series.stops.length} 站</span><span>${escapeGuideText(series.duration)}</span></div></button>`).join('');
  shrineGrid.innerHTML=FEATURED_SHRINES.map((shrine,index)=>{const fact=SHRINE_FACTS[shrine[1]]||{};return`<article class="featured-shrine-card"><span>${String(index+1).padStart(2,'0')}</span><div><small>${escapeGuideText(shrine[2])} · ${escapeGuideText(shrine[3])}</small><h3>${escapeGuideText(shrine[0])}</h3><p class="detail-alias">${escapeGuideText(shrine[1])}</p><p>${escapeGuideText(shrine[4])}</p><dl class="shrine-fact-list"><div><dt>御祭神／本尊</dt><dd>${escapeGuideText(fact.deity||'待官方核對')}</dd></div><div><dt>社務／授與時間</dt><dd>${escapeGuideText(fact.hours||'待官方核對')}</dd></div><div><dt>地址</dt><dd>${escapeGuideText(fact.address||'待官方核對')}</dd></div><div><dt>主要祈願</dt><dd>${escapeGuideText(fact.prayer||'待官方核對')}</dd></div><div><dt>御朱印</dt><dd>${escapeGuideText(fact.goshuin||'待官方核對')}</dd></div></dl><small class="verified-date">最後核對：${escapeGuideText(fact.checked||'待確認')}</small><a href="${shrine[5]}" target="_blank" rel="noopener">查閱來源 →</a></div></article>`}).join('');
  researchGrid.innerHTML=PILGRIMAGE_RESEARCH_CATALOG.map(item=>`<article><div><small>${escapeGuideText(item[1])} · ${escapeGuideText(item[2])}</small><h3>${escapeGuideText(item[0])}</h3><p>${escapeGuideText(item[3])}</p></div><a href="${item[4]}" target="_blank" rel="noopener">研究來源</a></article>`).join('');
  $$('[data-series]').forEach(button=>button.onclick=()=>openPilgrimageModal(button.dataset.series));
}
function openPilgrimageModal(id){
  const series=PILGRIMAGE_SERIES.find(item=>item.id===id);if(!series)return;
  $('#pilgrimageModalMeta').textContent=`${series.region} · ${series.season} · ${series.duration}`;
  $('#pilgrimageModalTitle').textContent=series.title;
  $('#pilgrimageModalHistory').textContent=series.history;
  $('#pilgrimageModalNote').innerHTML=`<p>重要提醒：${escapeGuideText(series.note)}</p>`;
  $('#pilgrimageStopList').innerHTML=series.stops.map((stop,index)=>`<article><b>${index+1}</b><div><small>${escapeGuideText(stop[2])}</small><h3>${escapeGuideText(stop[0])}</h3><p class="detail-alias">${escapeGuideText(stop[1])}</p><p>${escapeGuideText(stop[3])}</p><a href="${stop[4]}" target="_blank" rel="noopener">查看這一站來源</a></div></article>`).join('');
  $('#pilgrimageSourceLink').href=series.sourceUrl;
  $('#pilgrimageModal').classList.remove('hidden');document.body.style.overflow='hidden';
}
function closePilgrimageModal(){$('#pilgrimageModal').classList.add('hidden');document.body.style.overflow=''}

function aliases(place){return [place.nameJa,place.nameEn].filter(Boolean).join(' · ')}
function placeCard(place,featuredMode=false){const selected=state.selected.has(place.id),metric=`完成度 ${place.completionScore}%${place.recommendationEligible?' · 可排行程':' · 待動態核對'}`;return `<article class="place-card ${featuredMode?'featured':''}" data-id="${place.id}" tabindex="0" aria-label="查看 ${place.name} 詳細介紹"><div class="place-art art-${place.zone}"><span>${place.emoji}</span><button class="save-place ${selected?'saved':''}" aria-label="${selected?'移除':'加入'} ${place.name}">${selected?'✓':'＋'}</button><small>${place.area}</small></div><div class="place-info"><div class="place-meta"><span>${place.category}</span><b>${metric}</b></div><h3>${place.name}</h3><small class="place-alias">${aliases(place)}</small><p>${place.desc}</p><div class="tag-row">${place.tags.slice(0,3).map(t=>`<span>${t}</span>`).join('')}</div></div></article>`}
function renderFeatured(){$('#featuredGrid').innerHTML=featured.map(p=>placeCard(p,true)).join('');bindPlaceCards()}
function renderFilters(){const cats=['全部',...new Set(ALL_PLACES.map(p=>p.category))];$('#categoryFilters').innerHTML=cats.map((c,i)=>`<button class="filter-chip ${i===0?'active':''}" data-category="${c}">${c}</button>`).join('');$$('.filter-chip').forEach(b=>b.onclick=()=>{$$('.filter-chip').forEach(x=>x.classList.remove('active'));b.classList.add('active');state.category=b.dataset.category;state.visiblePlaces=60;renderPlaces()})}
function passesQuality(place){if(state.dataQuality==='curated')return place.completionScore===100;if(state.dataQuality==='usable')return place.completionScore>=80;return place.completionScore<80}
function filteredPlaces(){const q=state.search.trim().toLowerCase();return ALL_PLACES.filter(p=>passesQuality(p)&&(state.category==='全部'||p.category===state.category)&&(!q||`${p.name} ${p.nameJa} ${p.nameEn} ${p.area} ${p.category} ${p.cuisine||''} ${p.tags.join(' ')}`.toLowerCase().includes(q))).sort((a,b)=>(Number(b.curated)-Number(a.curated))||(b.popularity-a.popularity))}
function renderPlaces(){const list=filteredPlaces(),visible=list.slice(0,state.visiblePlaces),label=state.dataQuality==='curated'?'完成度 100%':state.dataQuality==='usable'?'完成度至少 80%':'低於 80%';$('#placesGrid').innerHTML=visible.map(p=>placeCard(p)).join('');$('#placeCount').textContent=`${label}：${list.length.toLocaleString()} 個地點`;$('#loadMoreButton').classList.toggle('hidden',visible.length>=list.length);bindPlaceCards()}
function bindPlaceCards(){$$('.save-place').forEach(btn=>btn.onclick=e=>{e.stopPropagation();const id=btn.closest('.place-card').dataset.id;state.selected.has(id)?state.selected.delete(id):state.selected.add(id);renderFeatured();renderPlaces()});$$('.place-card').forEach(card=>{card.onclick=()=>openPlaceModal(card.dataset.id);card.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();openPlaceModal(card.dataset.id)}}})}
$$('#qualitySelector button').forEach(button=>button.onclick=()=>{$$('#qualitySelector button').forEach(item=>item.classList.remove('active'));button.classList.add('active');state.dataQuality=button.dataset.quality;state.visiblePlaces=60;renderPlaces()});

function openPlaceModal(id){const place=byId(id);if(!place)return;state.modalPlaceId=id;$('#modalPlaceTier').textContent=place.dataTier||'待稽核';$('#modalPlaceName').textContent=place.name;$('#modalPlaceAliases').textContent=aliases(place);$('#modalPlaceIntro').textContent=place.desc;const price=place.priceBand||(place.curated?(place.admission?`門票參考 ¥${place.admission.toLocaleString()}`:'免費或無門票'):'尚未人工確認');const facts=[['區域',place.area],['分類',place.category],['主題／類型',place.cuisine||place.tags[0]||'待確認'],['建議停留',place.curated?`約 ${place.duration} 分鐘`:'尚未人工確認'],['費用／價位',price],['營業時間',place.openingHours||'請查官方最新資訊'],...(place.branchUniqueness?[['這間分店的差異',place.branchUniqueness]]:[]),...(place.travelerReason?[['適合什麼旅客',place.travelerReason]]:[])];$('#modalPlaceFacts').innerHTML=facts.map(([key,value])=>`<div><dt>${key}</dt><dd>${value}</dd></div>`).join('');const warnings=[...(place.qualityReasons||[]),...(place.queueRisk?[`候位風險：${place.queueRisk}`]:[]),...(place.reservationNote?[place.reservationNote]:[])];$('#modalPlaceWarnings').innerHTML=warnings.slice(0,5).map(reason=>`<p>⚠ ${reason}</p>`).join('');const source=place.officialUrl||place.sourceUrl||`https://www.google.com/maps/search/?api=1&query=${place.lat},${place.lng}`;$('#modalSourceLink').href=source;$('#modalMapButton').classList.toggle('hidden',place.category!=='神社寺廟');$('#modalSaveButton').textContent=state.selected.has(id)?'從行程候選移除':'加入行程候選';$('#placeModal').classList.remove('hidden');document.body.style.overflow='hidden'}
function closePlaceModal(){$('#placeModal').classList.add('hidden');document.body.style.overflow='';state.modalPlaceId=null}
$('#closePlaceModal').onclick=closePlaceModal;$('[data-close-modal]').onclick=closePlaceModal;$('#modalSaveButton').onclick=()=>{const id=state.modalPlaceId;if(!id)return;state.selected.has(id)?state.selected.delete(id):state.selected.add(id);openPlaceModal(id);renderFeatured();renderPlaces()};document.addEventListener('keydown',event=>{if(event.key==='Escape'&&!$('#placeModal').classList.contains('hidden'))closePlaceModal()});
$('#modalMapButton').onclick=()=>{const id=state.modalPlaceId;closePlaceModal();showPlaceOnMap(id)};

function switchView(view){state.view=view;$$('.view').forEach(v=>v.classList.remove('active'));$(`#${view}View`).classList.add('active');$$('.nav-link').forEach(b=>b.classList.toggle('active',b.dataset.view===view));if(view==='map')requestAnimationFrame(()=>{initShrineMap();shrineMap?.invalidateSize()});window.scrollTo({top:0,behavior:'smooth'})}
$$('[data-view]').forEach(b=>b.addEventListener('click',()=>switchView(b.dataset.view)));
$$('#paceSelector button').forEach(b=>b.onclick=()=>{$$('#paceSelector button').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');state.pace=b.dataset.value});
$$('#partySelector button').forEach(b=>b.onclick=()=>{const v=b.dataset.value;if(v==='adult'){state.party=new Set(['adult']);$$('#partySelector button').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');return}state.party.delete('adult');$('#partySelector [data-value="adult"]').classList.remove('selected');state.party.has(v)?state.party.delete(v):state.party.add(v);b.classList.toggle('selected');if(!state.party.size){state.party.add('adult');$('#partySelector [data-value="adult"]').classList.add('selected')}});

const THEME_WORDS={
  food:['美食','吃','壽司','拉麵','燒肉','甜點','市場','居酒屋'],shopping:['購物','血拼','免稅','藥妝','百貨','outlet','伴手禮'],
  shrine:['神社','寺廟','御守','鳥居','文化','古蹟'],anime:['動漫','動畫','寶可夢','任天堂','鋼彈','扭蛋','電器'],
  nature:['自然','公園','花','櫻','海景','富士山'],night:['夜景','展望台','夜生活'],family:['小孩','親子','迪士尼','樂園']
};
const THEME_CATEGORIES={food:['美食市場','特色餐廳'],shopping:['購物血拼'],shrine:['神社寺廟','歷史文化'],anime:['動漫娛樂'],nature:['公園自然'],night:['展望夜景'],family:['主題樂園','動漫娛樂']};
const FOOD_TERMS=['壽司','迴轉壽司','北海道海鮮','江戶前','燒肉','壽喜燒','涮涮鍋','火鍋','鍋物','居酒屋','拉麵','沾麵','擔擔麵','燒鳥','串燒','螃蟹','和牛','牛舌','天婦羅','天丼','豬排','鰻魚','蕎麥麵','文字燒','洋食','咖哩','海鮮','創意料理','法國料理','甜點','咖啡'];
const NEARBY_ZONES=['chiba','kamakura','yokohama','hakone','fuji','nikko','kawagoe','karuizawa'];
const CITY_ZONES=['asakusa','ueno','central','shibuya','shinjuku','minato','bay','ikebukuro','west','east'];
const ZONE_KEYWORDS={chiba:['迪士尼','舞濱','千葉','成田'],kamakura:['鎌倉','江之島','江島'],yokohama:['橫濱'],hakone:['箱根'],fuji:['富士山','河口湖','忍野','御殿場'],nikko:['日光'],kawagoe:['川越'],karuizawa:['輕井澤'],asakusa:['淺草','晴空塔'],ueno:['上野','阿美橫','秋葉原','湯島'],central:['築地','銀座','東京站','皇居','日本橋','八重洲'],shibuya:['澀谷','原宿','明治神宮','青山'],shinjuku:['新宿'],minato:['東京鐵塔','六本木','麻布台','麻布'],bay:['豐洲','台場','門前仲町'],ikebukuro:['池袋','大塚'],west:['吉祥寺','下北澤','豪德寺','中野','池上','戶越'],east:['柴又','帝釋天']};

function includesAny(text,words){return words.some(w=>text.toLowerCase().includes(w.toLowerCase()))}
function parseRequest(text){const negative={food:['不想吃','不要美食'],shopping:['不想購物','不要購物','不血拼','不買東西'],shrine:['不想逛神社','不要寺廟'],anime:['不看動漫','不喜歡動漫'],nature:['不想看自然'],night:['不看夜景'],family:['不要樂園']};const themes=Object.entries(THEME_WORDS).filter(([key,words])=>includesAny(text,words)&&!includesAny(text,negative[key]||[])).map(([key])=>key);if(!themes.length)themes.push('food','shopping','shrine');const mentionedZones=Object.entries(ZONE_KEYWORDS).filter(([,words])=>includesAny(text,words)).map(([zone])=>zone);const musts=ALL_PLACES.filter(p=>includesAny(text,[p.name,...p.name.split('・'),p.nameJa,p.nameEn])).map(p=>p.id);const foodTerms=FOOD_TERMS.filter(term=>includesAny(text,[term]));return{themes,mentionedZones,musts,foodTerms}}
function scorePlace(place,request){let score=place.popularity;for(const theme of request.themes)if((THEME_CATEGORIES[theme]||[]).includes(place.category)||place.tags.some(t=>THEME_WORDS[theme]?.some(w=>t.includes(w))))score+=60;const foodText=`${place.name} ${place.nameJa} ${place.cuisine||''} ${place.tags.join(' ')}`;if(request.foodTerms.some(term=>foodText.includes(term)))score+=160;if(request.musts.includes(place.id))score+=1000;if(state.selected.has(place.id))score+=500;if((state.party.has('elderly')||state.party.has('stroller'))&&['整日','階梯'].some(t=>place.tags.includes(t)))score-=25;return score}
function rankZones(zones,request){return zones.map(zone=>{const ps=RECOMMENDATION_PLACES.filter(p=>p.zone===zone).sort((a,b)=>scorePlace(b,request)-scorePlace(a,request));return{zone,score:(request.mentionedZones.includes(zone)?500:0)+(ps.slice(0,3).reduce((s,p)=>s+scorePlace(p,request),0)/3||0)}}).sort((a,b)=>b.score-a.score).map(x=>x.zone)}
function generateItinerary(){
  const days=Number($('#days').value),text=$('#tripPrompt').value,request=parseRequest(text);state.preferences=request.themes;
  let desired=state.pace==='leisurely'?3:state.pace==='intensive'?5:4;if(state.party.has('elderly')||state.party.has('child')||state.party.has('stroller'))desired=Math.max(2,desired-1);
  const requestedNearby=rankZones(NEARBY_ZONES.filter(z=>request.mentionedZones.includes(z)),request).slice(0,Math.max(0,days-2));
  const cityDays=days-requestedNearby.length,cityOrder=rankZones(CITY_ZONES,request),mustZones=[...new Set(ALL_PLACES.filter(p=>request.musts.includes(p.id)||state.selected.has(p.id)).map(p=>p.zone).filter(z=>CITY_ZONES.includes(z)))];
  const chosenCity=[...new Set([...mustZones,...cityOrder])].slice(0,cityDays),chosen=[...chosenCity,...requestedNearby];
  const used=new Set();state.itinerary=chosen.map(zone=>RECOMMENDATION_PLACES.filter(p=>p.zone===zone).sort((a,b)=>scorePlace(b,request)-scorePlace(a,request)).filter(p=>!used.has(p.id)).slice(0,NEARBY_ZONES.includes(zone)?Math.min(3,desired):desired).map(p=>(used.add(p.id),p)));
  state.activeDay=0;renderTrip();
}
function timeAdd(time,min){let[h,m]=time.split(':').map(Number),total=h*60+m+min;return`${String(Math.floor(total/60)).padStart(2,'0')}:${String(total%60).padStart(2,'0')}`}
function distance(a,b){if(!a||!b)return 0;const r=6371,dLat=(b.lat-a.lat)*Math.PI/180,dLon=(b.lng-a.lng)*Math.PI/180,x=Math.sin(dLat/2)**2+Math.cos(a.lat*Math.PI/180)*Math.cos(b.lat*Math.PI/180)*Math.sin(dLon/2)**2;return r*2*Math.atan2(Math.sqrt(x),Math.sqrt(1-x))}
function mealBudget(){const budget=Number($('#budget').value);return budget<=6000?2500:budget<=10000?4000:budget<=16000?6000:8000}
function dayMetrics(day){let walk=0,transitMinutes=0,localFare=0;day.forEach((p,i)=>{if(i){const leg=estimateTransportLeg(day[i-1],p);walk+=leg.mode==='步行'?leg.km:Math.min(leg.km,.45);transitMinutes+=leg.minutes;localFare+=leg.fare}});const admission=day.reduce((s,p)=>s+(p.admission||0),0),nearTransit=Math.max(0,...day.map(p=>p.transit||0)),transport=nearTransit||localFare,meals=mealBudget();return{walk:walk+day.length*.35,transitMinutes,admission,transport,meals,cost:admission+transport+meals,transportBasis:nearTransit?'近郊人工參考值':'東京 Metro IC 票價級距估算'}}
function dayAreaLabel(day){const areas=[...new Set(day.map(p=>p.area))];return areas.length<=2?areas.join('・'):`${areas[0]}等區域`}
function renderTrip(){const days=state.itinerary.length,all=state.itinerary.flat(),metrics=state.itinerary.map(dayMetrics),themeNames={food:'美食',shopping:'購物',shrine:'神社寺廟',anime:'動漫',nature:'自然',night:'夜景',family:'親子'};$('#resultDays').textContent=days;$('#totalStops').textContent=all.length;$('#totalCost').textContent='¥'+metrics.reduce((s,m)=>s+m.cost,0).toLocaleString();$('#totalWalk').textContent=metrics.reduce((s,m)=>s+m.walk,0).toFixed(1)+' km';$('#resultSummary').textContent=`偏好：${state.preferences.map(x=>themeNames[x]).join('、')} · 購物金額另計 · 依區域降低折返`;$('#dayTabs').innerHTML=state.itinerary.map((d,i)=>`<button class="day-tab ${i===state.activeDay?'active':''}" data-day="${i}"><b>DAY ${i+1}</b><span>${dayAreaLabel(d)}</span><small>${d.length} 個地點 · 約 ${metrics[i].walk.toFixed(1)} km</small></button>`).join('');$$('.day-tab').forEach(b=>b.onclick=()=>{state.activeDay=Number(b.dataset.day);renderDay()});$('#emptyTrip').classList.add('hidden');$('#tripResult').classList.remove('hidden');renderDay();switchView('trip')}
function renderDay(){const day=state.itinerary[state.activeDay]||[],metrics=dayMetrics(day);$$('.day-tab').forEach((b,i)=>b.classList.toggle('active',i===state.activeDay));$('#dayArea').textContent=dayAreaLabel(day)||'東京';$('#dayTitle').textContent=`第 ${state.activeDay+1} 天 · ${state.pace==='leisurely'?'慢慢走':'順路玩'}`;let time=state.party.has('elderly')?'09:30':'09:00';const startTime=time;const stops=day.map((p,i)=>{const arrival=time,stay=p.duration+(state.party.has('elderly')?15:0);time=timeAdd(time,stay);let leg='';if(i<day.length-1){const estimate=estimateTransportLeg(p,day[i+1]);leg=`<div class="travel-leg"><span>↓</span> ${estimate.mode}約 ${estimate.minutes} 分鐘${estimate.fare?` · IC 票價級距約 ¥${estimate.fare}`:''} · 尚非即時班次</div>`;time=timeAdd(time,estimate.minutes+10)}const feeText=p.priceBand?`價位 ${p.priceBand}`:(p.admission?'門票參考 ¥'+p.admission.toLocaleString():'免費或無門票');return`<article class="timeline-stop"><time>${arrival}</time><div class="stop-marker">${i+1}</div><div class="stop-card"><div><span class="stop-category">${p.category}</span><h3>${p.emoji} ${p.name}</h3><small class="place-alias">${aliases(p)}</small><p>${p.desc}</p></div><div class="stop-detail"><span>停留約 ${Math.round(stay/10)*10} 分鐘</span><span>${feeText}</span><button class="show-stop-detail" data-id="${p.id}">查看完整介紹</button></div></div>${leg}</article>`}).join('');const schedule=`<div class="schedule-banner"><div><b>今日 Schedule｜${startTime}–${time}</b><span>${day.length} 站 · 移動約 ${metrics.transitMinutes} 分鐘 · 步行約 ${metrics.walk.toFixed(1)} km</span></div><div><b>用餐與休息</b><span>午餐保留 60 分鐘；長者／親子模式每 90–120 分鐘檢查休息</span></div></div>`;$('#timeline').innerHTML=schedule+stops+`<div class="day-total"><b>今日基本旅費</b><span>餐食預算 ¥${metrics.meals.toLocaleString()}</span><span>交通暫估 ¥${metrics.transport.toLocaleString()}</span><span>門票 ¥${metrics.admission.toLocaleString()}</span><strong>合計 ¥${metrics.cost.toLocaleString()}</strong><small>${metrics.transportBasis}；不含住宿、機票與個人購物。<a href="${TRANSPORT_REFERENCE.tokyoMetro.sourceUrl}" target="_blank" rel="noopener">官方票價依據</a></small></div>`;$$('.show-stop-detail').forEach(button=>button.onclick=()=>openPlaceModal(button.dataset.id))}

$('#plannerForm').addEventListener('submit',e=>{e.preventDefault();const overlay=$('#loadingOverlay'),messages=['解析美食、購物與文化偏好…','依人氣與區域挑選地點…','避免市區與近郊混排…','拆分餐食、交通與門票…'];overlay.classList.remove('hidden');let i=0;$('#loadingText').textContent=messages[0];const timer=setInterval(()=>{$('#loadingText').textContent=messages[++i%messages.length]},350);setTimeout(()=>{clearInterval(timer);generateItinerary();overlay.classList.add('hidden')},1200)});
$('#regenerateButton').onclick=()=>{state.activeDay=0;switchView('planner')};
$('#placeSearch').addEventListener('input',event=>{state.search=event.target.value;state.visiblePlaces=60;renderPlaces()});
$('#loadMoreButton').onclick=()=>{state.visiblePlaces+=60;renderPlaces()};

function escapeMapText(value=''){return String(value).replace(/[&<>'"]/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[char]))}
function mapFilteredPlaces(){const q=state.mapSearch.trim().toLowerCase();return SHRINE_PLACES.filter(place=>!q||`${place.name} ${place.nameJa||''} ${place.nameEn||''} ${place.area} ${(place.tags||[]).join(' ')}`.toLowerCase().includes(q)).sort((a,b)=>(Number(b.completionScore)-Number(a.completionScore))||(b.popularity-a.popularity))}
function markerPopup(place){return `<div class="map-popup"><b>${escapeMapText(place.name)}</b><small>${escapeMapText(aliases(place))}</small><span>${escapeMapText(place.area)} · 完成度 ${place.completionScore}%</span><button data-map-detail="${escapeMapText(place.id)}">查看完整資訊</button></div>`}
function renderMapList(){const places=mapFilteredPlaces();$('#mapPlaceTotal').textContent=SHRINE_PLACES.length.toLocaleString();$('#mapResultCount').textContent=`${places.length.toLocaleString()} 間寺社`;$('#mapPlaceList').innerHTML=places.slice(0,200).map(place=>`<button class="map-place-item" data-map-place="${place.id}"><span>${place.emoji}</span><div><b>${escapeMapText(place.name)}</b><small>${escapeMapText(place.area)} · ${escapeMapText(place.nameJa||'日文名待補')}</small></div><em>${place.completionScore}%</em></button>`).join('')||'<p class="map-empty">找不到符合條件的寺社。</p>';$$('[data-map-place]').forEach(button=>button.onclick=()=>focusMapPlace(button.dataset.mapPlace))}
function renderMapMarkers(){if(!shrineMap)return;const visibleIds=new Set(mapFilteredPlaces().map(place=>place.id));for(const [id,marker] of mapMarkers){if(visibleIds.has(id)){if(!shrineMap.hasLayer(marker))marker.addTo(shrineMap)}else if(shrineMap.hasLayer(marker))marker.removeFrom(shrineMap)}renderMapList()}
function initShrineMap(){if(shrineMap||typeof L==='undefined')return;shrineMap=L.map('shrineMap',{zoomControl:true,minZoom:5}).setView([35.6812,139.7671],10);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'&copy; OpenStreetMap contributors'}).addTo(shrineMap);SHRINE_PLACES.forEach(place=>{const marker=L.marker([place.lat,place.lng],{title:place.name}).bindPopup(markerPopup(place));marker.on('popupopen',()=>setTimeout(()=>{$$('[data-map-detail]').forEach(button=>button.onclick=()=>openPlaceModal(button.dataset.mapDetail))},0));mapMarkers.set(place.id,marker);marker.addTo(shrineMap)});renderMapList();fitAllShrines()}
function focusMapPlace(id){initShrineMap();const place=byId(id),marker=mapMarkers.get(id);if(!place||!marker)return;shrineMap.setView([place.lat,place.lng],16,{animate:true});marker.openPopup()}
function showPlaceOnMap(id){switchView('map');requestAnimationFrame(()=>focusMapPlace(id))}
function fitAllShrines(){initShrineMap();const visible=mapFilteredPlaces().map(place=>[place.lat,place.lng]);if(visible.length)shrineMap.fitBounds(visible,{padding:[24,24],maxZoom:12})}
$('#mapSearch').addEventListener('input',event=>{state.mapSearch=event.target.value;renderMapMarkers()});
$('#fitMapButton').onclick=fitAllShrines;
$('#locateMeButton').onclick=()=>{if(!navigator.geolocation){alert('此裝置不支援定位。');return}navigator.geolocation.getCurrentPosition(position=>{initShrineMap();const latlng=[position.coords.latitude,position.coords.longitude];if(userLocationMarker)userLocationMarker.remove();userLocationMarker=L.circleMarker(latlng,{radius:9,color:'#174c3d',fillColor:'#d8ef9c',fillOpacity:1}).addTo(shrineMap).bindPopup('你目前的位置').openPopup();shrineMap.setView(latlng,14)},()=>alert('無法取得位置，請在 iPhone 瀏覽器允許定位權限。'),{enableHighAccuracy:true,timeout:10000})};
$('#closePilgrimageModal').onclick=closePilgrimageModal;
$('[data-close-pilgrimage]').onclick=closePilgrimageModal;
document.addEventListener('keydown',event=>{if(event.key==='Escape'&&!$('#pilgrimageModal').classList.contains('hidden'))closePilgrimageModal()});
renderFeatured();renderFilters();renderPlaces();renderPilgrimageGuides();
