(function(root,factory){if(typeof module==='object'&&module.exports)module.exports=factory(require('./travel-graph'),require('./entity-resolver'));else root.AsakusaP0=factory(root.TravelGraph,root.EntityResolver)})(typeof globalThis!=='undefined'?globalThis:this,function(TravelGraph,EntityResolver){
  const CHECKED_AT='2026-08-01';
  const PLACES=[
    {id:'kaminarimon',name:'雷門',nameJa:'雷門',nameEn:'Kaminarimon Gate',area:'淺草',zone:'asakusa',category:'城市地標',emoji:'🏮',duration:20,admission:0,popularity:100,tags:['初訪必去','大紅燈籠','短停留'],desc:'淺草寺的入口地標；保留為獨立 Landmark，方便搜尋與安排停留。',lat:35.7111,lng:139.7964,officialUrl:'https://www.senso-ji.jp/guide/guide01.html',sourceCheckedAt:CHECKED_AT,completionScore:100,dataTier:'P0 已核對',curated:true,recommendationEligible:true,openingHours:'戶外地標；全天可到訪',requiresLiveCheck:false},
    {id:'asakusa-shrine',name:'淺草神社',nameJa:'浅草神社',nameEn:'Asakusa Shrine',area:'淺草',zone:'asakusa',category:'神社寺廟',emoji:'⛩',duration:35,admission:0,popularity:88,tags:['御朱印','三社樣','文化'],desc:'緊鄰淺草寺但屬不同宗教實體；御朱印行程應在社務時間內先參拜再受領。',lat:35.7151,lng:139.7974,officialUrl:'https://asakusajinja.jp/goshuin/',sourceCheckedAt:CHECKED_AT,completionScore:100,dataTier:'P0 已核對',curated:true,recommendationEligible:true,openingHours:'社務時間 平日 09:00–16:00；週末及國定假日 09:00–16:30',requiresLiveCheck:true},
    {id:'sumida-park-asakusa',name:'隅田公園（淺草側）',nameJa:'隅田公園',nameEn:'Sumida Park (Asakusa side)',area:'淺草',zone:'asakusa',category:'公園自然',emoji:'🌿',duration:45,admission:0,popularity:82,tags:['河岸','晴空塔景觀','長者可調整'],desc:'淺草側河岸散步區；可依體力縮短，雨天則改為室內展望與休息。',lat:35.7140,lng:139.8028,officialUrl:'https://www.city.taito.lg.jp/kenchiku/hanamidori/koen/shokai/sumidakoen.html',sourceCheckedAt:CHECKED_AT,completionScore:100,dataTier:'P0 已核對',curated:true,recommendationEligible:true,openingHours:'戶外公園；天候與活動需出發前確認',requiresLiveCheck:true},
    {id:'asakusa-culture-center',name:'淺草文化觀光中心',nameJa:'浅草文化観光センター',nameEn:'Asakusa Culture Tourist Information Center',area:'淺草',zone:'asakusa',category:'歷史文化',emoji:'🏛',duration:35,admission:0,popularity:84,tags:['室內雨天','免費展望','休息','親子','無障礙'],desc:'雷門正對面的室內起點，提供觀光資訊、廁所、授乳室與免費展望；適合先確認當日狀況。',lat:35.7107,lng:139.7966,officialUrl:'https://www.city.taito.lg.jp/bunka_kanko/kankoinfo/info/oyakudachi/kankocenter/index.html',sourceCheckedAt:CHECKED_AT,completionScore:100,dataTier:'P0 已核對',curated:true,recommendationEligible:true,openingHours:'主要設施 09:00–20:00；8樓展望露台至 22:00',requiresLiveCheck:true}
  ];
  const ENTITIES=[{id:'asakusa',type:'TRAVEL_AREA'},...PLACES.map(place=>({id:place.id,type:place.id==='kaminarimon'?'LANDMARK':'PLACE'})),{id:'sensoji',type:'PLACE'},{id:'nakamise',type:'PLACE'},{id:'kappabashi',type:'TRAVEL_AREA'},{id:'daikokuya',type:'PLACE'}];
  const RELATIONSHIPS=[
    ['kaminarimon','BELONGS_TO','sensoji',{}],['kaminarimon','NEXT','nakamise',{walkMinutes:1}],['nakamise','NEXT','sensoji',{walkMinutes:5}],['sensoji','NEXT','asakusa-shrine',{walkMinutes:2}],['asakusa-shrine','NEXT','sumida-park-asakusa',{walkMinutes:8}],['asakusa-culture-center','NEXT','kaminarimon',{walkMinutes:1}],['sensoji','NEAR','daikokuya',{walkMinutes:7}],['sumida-park-asakusa','RAIN_ALTERNATIVE','asakusa-culture-center',{}],['kappabashi','RAIN_ALTERNATIVE','asakusa-culture-center',{}]
  ].map(([from,type,to,meta])=>({from,type,to,...meta,evidenceLevel:'OFFICIAL_OR_MEASURED_REFERENCE',checkedAt:CHECKED_AT}));
  const ALIASES=[
    {entityId:'asakusa',entityType:'TRAVEL_AREA',exactAliases:['淺草','浅草','asakusa'],resolution:'AREA_INTENT'},
    {entityId:'sensoji',entityType:'PLACE',exactAliases:['淺草寺','浅草寺','sensoji','senso-ji','淺草觀音'],resolution:'RESOLVED'},
    {entityId:'kaminarimon',entityType:'LANDMARK',exactAliases:['雷門','kaminarimon','淺草雷門'],fuzzyQueries:['大紅燈籠','東京大紅燈籠','淺草紅燈籠','有寫雷門的那間神社','寫雷門的神社','雷門那間神社'],resolution:'RESOLVED'},
    {entityId:'nakamise',entityType:'PLACE',exactAliases:['仲見世','仲見世商店街','nakamise'],resolution:'RESOLVED'},
    {entityId:'asakusa-shrine',entityType:'PLACE',exactAliases:['淺草神社','浅草神社','asakusa shrine','三社樣'],resolution:'RESOLVED'},
    {entityId:'sumida-park-asakusa',entityType:'PLACE',exactAliases:['隅田公園','隅田川河岸'],resolution:'RESOLVED'},
    {entityId:'kappabashi',entityType:'TRAVEL_AREA',exactAliases:['合羽橋','合羽橋道具街','かっぱ橋'],resolution:'RESOLVED'}
  ];
  const graph=TravelGraph.create({entities:ENTITIES,relationships:RELATIONSHIPS}),resolver=EntityResolver.create(ALIASES);
  function resolveKnowledge(text=''){const result=resolver.resolve(text);if(result.status==='UNRESOLVED')return[];return[{...result,input:String(text),knowledgeNote:result.entityId==='kaminarimon'?'雷門是淺草寺入口的門，不是神社；行程實體應連到淺草寺建築群。':null}]}
  function isOneDayPlanning(text=''){const value=String(text);return/(?:淺草|浅草|asakusa|雷門|大紅燈籠)/i.test(value)&&/(?:一日|1日|一天|行程|安排|規劃|排行程|怎麼玩|想去|想看)/.test(value)}
  function parse(text,form={}){if(!isOneDayPlanning(text))return null;const resolved=ALIASES.map(entry=>entry.exactAliases.find(alias=>String(text).toLowerCase().includes(alias.toLowerCase()))).filter(Boolean);const goshuin=/御朱印|朱印/.test(text),rain=/下雨|雨天|雨備/.test(text),family=/親子|小孩|兒童|嬰兒車/.test(text),senior=/長者|長輩|老人|爸媽|父母|媽媽|爸爸|少走|走不動|不要太累/.test(text),pace=/悠閒|輕鬆|慢慢|不要太累/.test(text)?'LEISURELY':/充實|多排|緊湊/.test(text)?'INTENSIVE':'BALANCED';return{aiUnavailable:false,parserMode:'LOCAL_KNOWLEDGE',parserSource:'P0 淺草知識庫',themes:[...(goshuin?['shrine']:[]),...(family?['family']:[]),'classic'],excludedThemes:[],mentionedZones:['asakusa'],musts:[],foodTerms:[],clock:{start:form.startTime||'09:00',end:form.endTime||'19:00'},unsupported:[],localFlags:{rain,family,senior,goshuin},travelRequirements:{destination:['淺草'],tripDays:1,travelers:{adults:senior?[]:[1],seniors:senior?[1]:[],children:family?[1]:[],mobilityNeeds:senior?['少走路']:[]},interests:[...(goshuin?['shrine']:[]),...(family?['family']:[]),'classic'],mustVisit:resolved,foodPreferences:[],collectionGoals:goshuin?['御朱印']:[],shoppingGoals:[],dayConstraints:[],missingFields:[],requirements:[{id:'p0-area',kind:'DESTINATION',value:'淺草',normalizedValue:'asakusa',priority:'MUST',source:'USER_TEXT',evidence:'P0 alias registry',confidence:1,resolvedZone:'asakusa'}],religiousSitePreference:{primaryInterest:goshuin,accepted:true},mobilityProfile:{seniorPresent:senior},pace,budget:form.budget||null,clarifications:[],warnings:rain?['雨天模式：河岸改為室內展望與休息']:[]}}}
  function plan({requirements,dates,places,flags={}}){const byId=id=>places.find(place=>place.id===id),profile=requirements.mobilityProfile?.seniorPresent?'SENIOR':(requirements.travelers?.children||[]).length?'FAMILY':requirements.pace==='LEISURELY'?'LEISURELY':requirements.pace==='INTENSIVE'?'INTENSIVE':'BALANCED',goshuin=Boolean(requirements.collectionGoals?.length),rain=Boolean(flags.rain),ids=profile==='SENIOR'?['asakusa-culture-center','kaminarimon','sensoji','daikokuya',rain?'asakusa-culture-center':'sumida-park-asakusa']:profile==='LEISURELY'?['asakusa-culture-center','kaminarimon','sensoji','daikokuya',rain?'asakusa-culture-center':'sumida-park-asakusa']:profile==='FAMILY'?['asakusa-culture-center','kaminarimon','nakamise','sensoji','daikokuya',rain?'asakusa-culture-center':'sumida-park-asakusa']:['asakusa-culture-center','kaminarimon','nakamise','sensoji',...(goshuin?['asakusa-shrine']:[]), 'daikokuya',...(rain?[]:['sumida-park-asakusa']),...(requirements.pace==='INTENSIVE'?['kappabashi']:[])],seen=new Set(),selected=ids.map(byId).filter(place=>place&&!seen.has(place.id)&&seen.add(place.id));const items=selected.map((place,index)=>({placeId:place.id,name:place.name,zone:'asakusa',category:place.category,estimatedDuration:place.duration,selectionSource:index<4?'P0_CORE':'P0_PROFILE',sourceRequirementIds:['p0-area'],openingHoursStatus:place.requiresLiveCheck?'VERIFIED_REFERENCE':'OPEN_REFERENCE',travelFromPrevious:{mode:index?'walk':'start',minutes:index?RELATIONSHIPS.find(edge=>edge.from===selected[index-1].id&&edge.to===place.id)?.walkMinutes||8:0,walkingKm:index?0.35:0,fare:0}})),errors=[];if(!items.some(item=>item.placeId==='sensoji'))errors.push({code:'MISSING_P0_CORE'});if(new Set(items.map(item=>item.placeId)).size!==items.length)errors.push({code:'DUPLICATE_PLACE'});if(profile==='SENIOR'&&items.length>5)errors.push({code:'SENIOR_DENSITY'});if(goshuin&&!items.some(item=>item.placeId==='asakusa-shrine'))errors.push({code:'MISSING_GOSHUIN_WINDOW'});const requestedStart=requirements.dailyStartTime||'09:00',requestedEnd=requirements.dailyEndTime||'19:00',startTime=profile==='SENIOR'&&requestedStart<'09:30'?'09:30':requestedStart,endTime=profile==='SENIOR'&&requestedEnd>'18:00'?'18:00':requestedEnd,day={dayNumber:1,date:dates[0],title:'淺草一日智能旅遊',dayType:'full',startTime,endTime,items};return{ok:errors.length===0,itinerary:{tripDays:1,days:[day]},validation:{valid:errors.length===0,errors,metrics:{profile,stops:items.length,rainMode:rain}},repairApplied:false,traceability:[{id:'p0-area',priority:'MUST',status:'SATISFIED',value:'淺草',evidence:['所有行程節點均位於淺草 P0 Graph']}],policy:{profile,latestEndTime:day.endTime},selectionAudit:{items},stages:['Alias Resolution','P0 Graph Traversal','Profile Scheduling','Validation','Traceability']}}
  return{CHECKED_AT,PLACES,RELATIONSHIPS,ALIASES,graph,resolver,resolveKnowledge,isOneDayPlanning,parse,plan};
});
