let pendingUnderstanding=null,pendingPlannerContext='',dayRouteMap=null,dayRouteLayer=null;
const completedStops=new Set(JSON.parse(localStorage.getItem('tabi-completed-stops')||'[]'));
const companionMemory=JSON.parse(localStorage.getItem('tabi-companion-memory')||'{"trips":[]}');
const themeLabels={food:'美食',shopping:'購物',shrine:'寺社／御朱印',anime:'動漫',nature:'自然',night:'夜景',family:'親子／樂園',classic:'經典景點'};
function saveCompleted(){localStorage.setItem('tabi-completed-stops',JSON.stringify([...completedStops]));saveCompanionMemory()}
function saveCompanionMemory(){if(!state.tripDates?.length||!state.itinerary?.length)return;const tripId=`${state.tripDates[0]}::${state.tripDates.at(-1)}`,all=state.itinerary.flat(),done=all.filter(p=>state.tripDates.some(date=>completedStops.has(`${date}::${p.id}`))),record={id:tripId,start:state.tripDates[0],end:state.tripDates.at(-1),completedCount:done.length,religiousCount:done.filter(p=>p.category==='神社寺廟').length,updatedAt:new Date().toISOString()};const index=companionMemory.trips.findIndex(x=>x.id===tripId);index>=0?companionMemory.trips[index]=record:companionMemory.trips.push(record);companionMemory.trips=companionMemory.trips.slice(-20);localStorage.setItem('tabi-companion-memory',JSON.stringify(companionMemory))}
function memoryText(){const trips=companionMemory.trips||[];if(!trips.length)return'這是本裝置的第一趟旅程';const last=trips[trips.length-1];return`本裝置記得 ${trips.length} 趟旅程；最近一次完成 ${last.completedCount||0} 個地點${last.religiousCount?`、寺社 ${last.religiousCount} 間`:''}`}
function understandingHtml(request){const days=dateRange($('#tripStartDate').value,$('#tripEndDate').value).length,party=[...state.party].map(x=>({adult:'一般成人',elderly:'長者',child:'兒童',stroller:'嬰兒車'}[x])).join('、'),preference=request.travelRequirements?.religiousSitePreference,religious=preference?.primaryInterest?'寺社是主要旅行目標':preference?.accepted?'可安排寺社，但不是主要偏好':'不主動安排寺社',constraints=(request.travelRequirements?.dayConstraints||[]).map(item=>item.source||item.value||item.type).join('、')||'無',themes=Array.isArray(request.themes)?request.themes:[];return`<dl><div><dt>旅行日期</dt><dd>${$('#tripStartDate').value}～${$('#tripEndDate').value}（${days}天）</dd></div><div><dt>每天時間</dt><dd>${request.clock.start}～${request.clock.end}</dd></div><div><dt>特定日限制</dt><dd>${constraints}</dd></div><div><dt>偏好</dt><dd>${themes.map(x=>themeLabels[x]||x).join('、')||'尚未指定'}</dd></div><div><dt>寺社條件</dt><dd>${religious}</dd></div><div><dt>同行者</dt><dd>${party||'尚未指定'}</dd></div><div><dt>每日預算</dt><dd>約 ¥${Number($('#budget').value).toLocaleString()}</dd></div></dl>`}
function inputGateContext(){const dates=dateRange($('#tripStartDate').value,$('#tripEndDate').value);return{defaultDestination:'東京',tripDays:dates.length,dates:{start:dates[0]||null,end:dates.at(-1)||null},budget:Number($('#budget').value),hasItinerary:false}}
const understandingHtmlBase=understandingHtml;
understandingHtml=function(request){const base=understandingHtmlBase(request),requirements=request.travelRequirements,sourceLabels={USER_FORM:'依你最後手動設定',USER_TEXT:'依文字描述',AI_EXTRACTED:'依文字理解',DEFAULT:'目前預設'},paceLabels={LEISURELY:'悠閒',BALANCED:'均衡',INTENSIVE:'充實'},partyLabels={adult:'一般成人',elderly:'長者',child:'兒童',stroller:'嬰兒車'},fields=state.normalizedTripRequirements.fields,conflicts=state.normalizedTripRequirements.conflicts||[],fieldSummary=`步調：${paceLabels[fields.pace?.value]||'均衡'}（${sourceLabels[fields.pace?.source]}）・同行者：${(fields.party?.value||[]).map(value=>partyLabels[value]||value).join('、')||'未指定'}（${sourceLabels[fields.party?.source]}）・時間：${fields.startTime?.value}～${fields.endTime?.value}`,clarifications=requirements?.clarifications||[],groups=[['城市／地區',[...(requirements?.destination||[]),requirements?.hotelArea].filter(Boolean)],['指定景點',requirements?.mustVisit||[]],['想吃',requirements?.foodPreferences||[]],['購物',requirements?.shoppingGoals||[]],['動漫／收藏',[...(requirements?.interests||[]),...(requirements?.collectionGoals||[])].filter(Boolean)],['不想安排',requirements?.avoidances||[]],['特殊需求',[...(requirements?.travelers?.mobilityNeeds||[]),...(requirements?.warnings||[])].filter(Boolean)]],details=groups.filter(([,values])=>values.length).map(([label,values])=>`<div><dt>${label}</dt><dd>${escapeGuideText([...new Set(values)].join('、'))}</dd></div>`).join('');const conflictHtml=conflicts.length?`<section class="requirement-conflicts"><h3>偵測到 ${conflicts.length} 項設定不同</h3>${conflicts.map((item,index)=>`<div data-conflict="${index}"><p>文字描述：${escapeGuideText(String(item.textValue))}<br>目前選項：${escapeGuideText(String(item.formValue))}</p><button type="button" data-resolve-conflict="${index}:TEXT">以文字為準</button><button type="button" data-resolve-conflict="${index}:FORM">以目前選項為準</button><button type="button" data-resolve-conflict="${index}:COMPROMISE">讓 AI 折衷</button></div>`).join('')}</section>`:'';return base.replace('</dl>',`${details}<div><dt>目前設定</dt><dd>${escapeGuideText(fieldSummary)}</dd></div><div><dt>規劃前提醒</dt><dd>${clarifications.length?clarifications.map(escapeGuideText).join('；'):'目前沒有需要補充的項目'}</dd></div></dl>${conflictHtml}`)};
function bindConflictControls(){$$('[data-resolve-conflict]').forEach(button=>button.onclick=()=>{const[index,choice]=button.dataset.resolveConflict.split(':'),conflict=state.normalizedTripRequirements.conflicts[Number(index)];TripRequirementsState.resolve(state.normalizedTripRequirements,Number(index),choice);if(choice!=='FORM')state.manualRequirementFields.delete(conflict.field);saveNormalizedRequirements();const section=button.closest('[data-conflict]');section.innerHTML=`<p>已選擇：${choice==='TEXT'?'以文字描述為準':choice==='FORM'?'以目前選項為準':'使用折衷設定'}</p>`;syncFormFromRequirements()})}
function appendPlannerMessage(text,role='ai'){const box=$('#plannerConversation');if(!box||!text)return;const message=document.createElement('p');message.className=`planner-message ${role==='user'?'user-message':'ai-message'}`;message.textContent=text;box.append(message);message.scrollIntoView({behavior:'smooth',block:'end'})}
function setCompanionResponse({stateName='COMPLETED',intent='GENERAL_CHAT',text='',questions=[]}){const box=$('#companionResponse');box.dataset.state=stateName;$('#companionResponseLabel').textContent=stateName==='UNDERSTANDING'?'正在理解…':stateName==='ANSWERING'?'正在回答…':stateName==='PLANNING'?'準備規劃…':InputRouting.publicLabel(intent);$('#companionResponseText').textContent=text;$('#companionResponseQuestions').innerHTML=(questions||[]).map(question=>`<span>${escapeGuideText(question)}</span>`).join('');box.classList.remove('hidden')}
function setPlannerButtonBusy(busy){const button=$('#plannerForm .primary-button');button.disabled=busy;button.querySelector('span').textContent=busy?'請稍等…':'送出'}
async function routeCompanionInput(message){
    if(typeof AsakusaP0!=='undefined'&&AsakusaP0.isOneDayPlanning(message))return{intent:'TRIP_PLANNING',response:'已辨識為淺草一日遊；這項 P0 可直接使用本機知識庫規劃。',shouldPlan:true,questions:[],safetyLevel:'SAFE',reasonCode:'P0_LOCAL_KNOWLEDGE'};
  const base=String(window.TABI_CONFIG?.smartApiBaseUrl||'').replace(/\/$/,'');if(!base)throw new Error('AI_GATEWAY_NOT_CONFIGURED');
  const payload={message,formState:requirementsFormSnapshot(),context:{surface:'PLANNER_HOME',hasExistingItinerary:Boolean(state.itinerary.length),supportedDestination:'東京',language:'zh-TW'}},controller=new AbortController(),timer=setTimeout(()=>controller.abort(),25000);
  try{const response=await fetch(`${base}/api/input/route`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(payload),signal:controller.signal});if(!response.ok)throw new Error(`HTTP_${response.status}`);const result=await response.json(),validation=InputRouting.validate(result.route);if(!validation.valid)throw new Error(`INVALID_ROUTE_${validation.errors.join('_')}`);return validation.value}finally{clearTimeout(timer)}
}
async function startCompanionPlanning(){
  const answer=$('#tripPrompt').value.trim();if(!answer)return;const raw=pendingPlannerContext?`${pendingPlannerContext}\n補充回答：${answer}`:answer;appendPlannerMessage(answer,'user');$('#tripPrompt').value='';clearPlannerValidationError();setPlannerButtonBusy(true);setCompanionResponse({stateName:'UNDERSTANDING',intent:'GENERAL_CHAT',text:'我先理解你的需求。'});
  try{
    const route=await routeCompanionInput(raw);state.lastInputRoute=route;setCompanionResponse({stateName:InputRouting.uiStateFor(route.intent),intent:route.intent,text:route.response,questions:route.questions});
    appendPlannerMessage([route.response,...(route.questions||[])].filter(Boolean).join(' '));
    if(!route.shouldPlan){pendingPlannerContext=route.questions?.length?raw:'';$('#tripPrompt').placeholder=route.questions?.[0]||'繼續告訴我你的需求';$('#tripPrompt').focus();return}
    pendingPlannerContext='';$('#tripPrompt').placeholder='例如：幫我排淺草一日遊，帶媽媽，不要太累';
    setCompanionResponse({stateName:'PLANNING',intent:route.intent,text:'我會先整理你的需求，再讓你確認後開始規劃。'});
    const overlay=$('#loadingOverlay');overlay.classList.remove('hidden');$('#loadingText').textContent=typeof AsakusaP0!=='undefined'&&AsakusaP0.isOneDayPlanning(raw)?'正在讀取淺草 P0 知識庫…':'AI 正在整理你的旅行需求…';
    pendingUnderstanding=await smartParseRequest(raw);
    if(pendingUnderstanding.aiUnavailable){
      setCompanionResponse({stateName:'UNAVAILABLE',intent:'SYSTEM_ERROR',text:'旅行需求整理服務暫時沒有回應，請稍後再試一次。你的文字、日期與其他設定都已保留。'});
      return;
    }
    state.request=pendingUnderstanding;
    if(pendingUnderstanding.parserMode==='LOCAL_KNOWLEDGE'&&pendingUnderstanding.travelRequirements?.tripDays===1){$('#tripEndDate').value=$('#tripStartDate').value;updateHolidayNotice()}
    const requirements=pendingUnderstanding.travelRequirements;
    const constraints=requirements.dayConstraints||[],everyStart=constraints.find(item=>item.dayNumber==='EVERY'&&item.type==='EARLIEST_START'),everyEnd=constraints.find(item=>item.dayNumber==='EVERY'&&item.type==='LATEST_END');
    const senior=Boolean(requirements.mobilityProfile?.seniorPresent||(requirements.travelers?.seniors||[]).length);
    const children=(requirements.travelers?.children||[]).length>0;
    const extracted={pace:requirements.pace,startTime:everyStart?.value||pendingUnderstanding.clock?.start,endTime:everyEnd?.value||pendingUnderstanding.clock?.end,party:[...(senior?['elderly']:[]),...(children?['child']:[])]};
    state.normalizedTripRequirements=TripRequirementsState.merge({base:state.normalizedTripRequirements,rawText:raw,extracted,form:requirementsFormSnapshot(),manualFields:[...state.manualRequirementFields]});
    syncFormFromRequirements();saveNormalizedRequirements();
    const unified=TripRequirementsState.plain(state.normalizedTripRequirements);
    pendingUnderstanding.normalizedTripRequirements=unified;pendingUnderstanding.clock={start:unified.startTime,end:unified.endTime};
    state.pace={LEISURELY:'leisurely',BALANCED:'balanced',INTENSIVE:'intensive'}[unified.pace]||state.pace;
    state.party=new Set(unified.party?.length?unified.party:['adult']);
    $('#aiUnderstanding').innerHTML=understandingHtml(pendingUnderstanding);$('#aiConfirmModal .detail-tier').textContent=pendingUnderstanding.parserMode==='LOCAL_KNOWLEDGE'?'P0 知識庫已理解你的需求':'AI 已理解你的需求';bindConflictControls();$('#aiConfirmModal').classList.remove('hidden');document.body.style.overflow='hidden';setCompanionResponse({stateName:'NEEDS_CONFIRMATION',intent:'TRIP_PLANNING',text:'我整理好了，請確認需求摘要；確認後才會開始排行程。'});
  }catch(error){setCompanionResponse({stateName:'UNAVAILABLE',intent:'SYSTEM_ERROR',text:'AI 旅行夥伴目前忙碌，暫時無法可靠理解這段內容。請稍後再試；你的文字、日期與其他設定都已保留。'});state.lastRouteError=String(error.message||error)}finally{$('#loadingOverlay').classList.add('hidden');setPlannerButtonBusy(false)}
}
$('#editUnderstanding').onclick=()=>{$('#aiConfirmModal').classList.add('hidden');document.body.style.overflow=''};
$('#confirmUnderstanding').onclick=async()=>{const unresolved=TripRequirementsState.unresolved(state.normalizedTripRequirements),questions=pendingUnderstanding?.travelRequirements?.clarifications||[];if(unresolved.length||questions.length){setCompanionResponse({stateName:'NEEDS_CONFIRMATION',intent:'NEEDS_CLARIFICATION',text:unresolved.length?'文字與表單有不同設定，請先選擇要以哪一邊為準。':'開始規劃前還需要你補充一點資訊。',questions:unresolved.length?[]:questions.slice(0,3)});return}$('#aiConfirmModal').classList.add('hidden');document.body.style.overflow='';const overlay=$('#loadingOverlay'),steps=['整合你指定的景點與收藏目標…','依區域分組，避免跨區折返…','檢查寺務所／社務所與營業時間…','安排交通、用餐與休息緩衝…','完成每日節奏與可編輯草稿…'];overlay.classList.remove('hidden');let index=0;$('#loadingText').textContent=steps[0];const timer=setInterval(()=>{$('#loadingText').textContent=steps[Math.min(++index,steps.length-1)]},650),originalSmart=smartParseRequest;smartParseRequest=async()=>pendingUnderstanding;try{const success=await generateItinerary();if(success){$('#aiChat').classList.remove('hidden');updateCompanionDashboard();setCompanionResponse({stateName:'COMPLETED',intent:'TRIP_PLANNING',text:`行程已完成，共 ${state.tripDates.length} 天。你可以逐日查看、調整順序與時間。`});$('#tripResult')?.scrollIntoView({behavior:'smooth',block:'start'})}else setCompanionResponse({stateName:'UNAVAILABLE',intent:'SYSTEM_ERROR',text:'這次沒有產生可安心使用的完整行程。你的需求與表單都已保留，可以稍後重試或回去調整。'})}catch{setCompanionResponse({stateName:'UNAVAILABLE',intent:'SYSTEM_ERROR',text:'規劃途中暫時中斷，沒有把不完整結果當成成功。你的需求與表單都已保留，請稍後再試。'})}finally{smartParseRequest=originalSmart;clearInterval(timer);overlay.classList.add('hidden')}};
function stopKey(dayIndex,placeId){return`${state.tripDates[dayIndex]}::${placeId}`}
function updateCompanionDashboard(){if(!state.itinerary.length)return;const day=state.itinerary[state.activeDay]||[],done=day.filter(p=>completedStops.has(stopKey(state.activeDay,p.id))).length,percent=day.length?Math.round(done/day.length*100):0;$('#todayCompletion').textContent=`${percent}%`;$('#companionGreeting').textContent=percent===100?'今天的旅程完成了，辛苦了！':new Date().getHours()<12?'早安，今天一起好好旅行。':'我還在，接下來也陪你走。';const steps=Number($('#todaySteps').value)||0;$('#todayAdvice').textContent=steps>=20000?'今天步數很高，建議先補水並休息20分鐘。':steps>=10000?'已走不少路，下一站前找地方坐一下吧。':`今天還有 ${Math.max(0,day.length-done)} 個地點，按自己的節奏前進。`;enhanceStopCards()}
function enhanceStopCards(){$$('.editable-stop').forEach(card=>{const index=Number(card.dataset.stopIndex),place=state.itinerary[state.activeDay]?.[index];if(!place||card.querySelector('.complete-stop'))return;const button=document.createElement('button');button.className='complete-stop';const key=stopKey(state.activeDay,place.id);button.textContent=completedStops.has(key)?'✓ 已完成':'○ 標示完成';button.onclick=()=>{completedStops.has(key)?completedStops.delete(key):completedStops.add(key);saveCompleted();updateCompanionDashboard()};card.querySelector('.stop-edit-actions')?.append(button)})}
const originalRenderDay=renderDay;renderDay=function(){originalRenderDay();updateCompanionDashboard()};
$('#todaySteps').oninput=()=>{localStorage.setItem('tabi-today-steps',$('#todaySteps').value);updateCompanionDashboard()};$('#todaySteps').value=localStorage.getItem('tabi-today-steps')||0;
async function refreshWeather(){const day=state.itinerary[state.activeDay]||[],center=day[0]||{lat:35.6812,lng:139.7671};$('#todayWeather').textContent='更新中…';try{const response=await fetch(`https://api.open-meteo.com/v1/forecast?latitude=${center.lat}&longitude=${center.lng}&current=temperature_2m,precipitation,weather_code&timezone=Asia%2FTokyo`),data=await response.json(),current=data.current;$('#todayWeather').textContent=`${Math.round(current.temperature_2m)}°C・降雨 ${current.precipitation}mm`;if(current.precipitation>0)$('#todayAdvice').textContent='目前可能下雨，建議優先室內景點；可在聊天室要求我重新安排。'}catch{$('#todayWeather').textContent='天氣暫時無法取得'}}
$('#weatherCard').onclick=refreshWeather;
$('#replanToday').onclick=async()=>{const day=state.itinerary[state.activeDay]||[];if(!day.length)return;$('#aiChat').classList.remove('hidden');$('#aiChat').classList.add('open');chatMessage('請依照今天的體力與天氣重新安排，但保留已完成地點。','user');const steps=Number($('#todaySteps').value)||0,unfinished=day.filter(p=>!completedStops.has(stopKey(state.activeDay,p.id)));if(steps>=15000&&unfinished.length>1){const removed=unfinished.at(-1);day.splice(day.indexOf(removed),1);renderTrip();persistTripState();chatMessage(`你今天已走 ${steps.toLocaleString()} 步，我先移除最後一站「${displayName(removed)}」，保留已完成地點並讓行程提早結束。`);return}await refreshWeather();chatMessage('我已保留既有行程與完成紀錄。若要更精準調整，直接告訴我「下雨改室內」、「減少一站」或想加入的類型。')};
function routeLegText(from,to){const leg=estimateTransportLeg(from,to);return`${leg.mode}約 ${leg.minutes} 分鐘${leg.fare?`・約 ¥${leg.fare}`:''}`}
function showTodayRoute(){const day=state.itinerary[state.activeDay]||[];if(!day.length)return;$('#dayRouteTitle').textContent=`${state.tripDates[state.activeDay]} 今日動線`;$('#dayRouteModal').classList.remove('hidden');document.body.style.overflow='hidden';setTimeout(()=>{if(!dayRouteMap)dayRouteMap=L.map('dayRouteMap').setView([day[0].lat,day[0].lng],12);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'&copy; OpenStreetMap'}).addTo(dayRouteMap);if(dayRouteLayer)dayRouteLayer.remove();dayRouteLayer=L.layerGroup().addTo(dayRouteMap);const points=day.map(p=>[p.lat,p.lng]);day.forEach((p,i)=>L.marker(points[i],{icon:L.divIcon({className:'route-number-icon',html:`<span>${i+1}</span>`,iconSize:[30,30]})}).addTo(dayRouteLayer).bindPopup(displayName(p)));L.polyline(points,{color:'#e76e46',weight:5,dashArray:'8 7'}).addTo(dayRouteLayer);dayRouteMap.fitBounds(points,{padding:[28,28]});dayRouteMap.invalidateSize();$('#dayRouteLegs').innerHTML=day.slice(1).map((p,i)=>`<div><b>${i+1} → ${i+2}</b><span>${routeLegText(day[i],p)}</span></div>`).join('')},80)}
$('#showDayRoute').onclick=showTodayRoute;$('#closeDayRoute').onclick=closeTodayRoute;$('[data-close-route]').onclick=closeTodayRoute;function closeTodayRoute(){$('#dayRouteModal').classList.add('hidden');document.body.style.overflow=''}
$('#startTodayTrip').onclick=()=>{const day=state.itinerary[state.activeDay]||[],next=day.find(p=>!completedStops.has(stopKey(state.activeDay,p.id)))||day[0];if(!next)return;const apple=/iPhone|iPad|Mac/.test(navigator.userAgent),url=apple?`https://maps.apple.com/?daddr=${next.lat},${next.lng}&dirflg=r`:`https://www.google.com/maps/dir/?api=1&destination=${next.lat},${next.lng}&travelmode=transit`;window.open(url,'_blank','noopener')};
function makeDiary(){const day=state.itinerary[state.activeDay]||[],done=day.filter(p=>completedStops.has(stopKey(state.activeDay,p.id))),steps=Number($('#todaySteps').value)||0,goshuin=done.filter(p=>p.category==='神社寺廟').length,metrics=dayMetrics(day);const text=`${state.tripDates[state.activeDay]}，今天走了約 ${steps.toLocaleString()} 步，完成 ${done.length}/${day.length} 個地點${done.length?`：${done.map(displayName).join('、')}`:''}。${goshuin?`寺社參拜 ${goshuin} 間，也替收藏旅程留下新的進度。`:''}今日基本花費估算約 ¥${metrics.cost.toLocaleString()}。旅程不必追求全部打卡，能按自己的節奏留下記憶，就是很好的一天。`;$('#travelDiary').innerHTML=`<h3>AI 今日旅行日記</h3><p>${escapeGuideText(text)}</p>`;$('#travelDiary').classList.remove('hidden');saveCompanionMemory();return text}
$('#makeDiary').onclick=makeDiary;$('#shareToday').onclick=async()=>{const text=makeDiary();if(navigator.share)await navigator.share({title:'我的日本旅行日記',text,url:location.href}).catch(()=>{});else{await navigator.clipboard.writeText(text);alert('旅行摘要已複製，可貼到 LINE、Threads 或 IG。')}};
$('#toggleChat').onclick=()=>$('#aiChat').classList.toggle('open');$('#closeChat').onclick=()=>$('#aiChat').classList.remove('open');
function chatMessage(text,role='ai'){const p=document.createElement('p');p.className=role==='user'?'user-message':'ai-message';p.textContent=text;$('#chatMessages').append(p);p.scrollIntoView({behavior:'smooth',block:'end'})}
let pendingChatAction=null;
function currentTravelDayNumber(){const today=todayLocal(),index=state.tripDates.indexOf(today);return index>=0?index+1:state.activeDay+1}
function chatDayContext(text){return ItineraryCore.resolveDayReference(text,{tripDays:state.tripDates.length,dates:state.tripDates,currentTravelDayNumber:currentTravelDayNumber(),activeDayNumber:state.activeDay+1})}
function itinerarySignature(){return JSON.stringify(state.itinerary.map(day=>(day||[]).map(place=>place.id)))}
function dayState(dayIndex){const day=state.itinerary[dayIndex],validation=currentValidation(),errors=validation.errors.filter(error=>error.dayNumber===dayIndex+1);return{exists:Array.isArray(day),count:Array.isArray(day)?day.length:0,dayType:state.structuredItinerary?.days?.[dayIndex]?.dayType||'full',errors,rendered:dayIndex!==state.activeDay||$$('.editable-stop').length===(day?.length||0)}}
function findMentionedPlace(text){return RECOMMENDATION_PLACES.find(place=>text.includes(displayName(place))||text.includes(place.nameJa||'__')||text.includes(place.nameEn||'__'))}
function confirmPending(text){return pendingChatAction&&/^(?:好|好的|是|可以|現在|幫我|開始|確定)/.test(text)}
function mutationFailure(reason='修改後的行程未通過完整性驗證'){return`這次修改失敗：${reason}；原行程已保留，我不會假裝已完成。`}
async function handleChat(text){
  const gate=TravelQuality.classifyInput(text,{hasItinerary:true});
  if(['NONSENSE_OR_GIBBERISH','OFF_TOPIC','ABUSIVE_LANGUAGE','UNSAFE_OR_INAPPROPRIATE_REQUEST'].includes(gate.type)){const replies={NONSENSE_OR_GIBBERISH:'我目前無法理解這段內容；請改說要調整哪一天與什麼內容，原行程未改動。',OFF_TOPIC:'謝謝你。我會留在這裡陪你處理旅行；原行程沒有改動。',ABUSIVE_LANGUAGE:'我不會和你對罵，也不會亂改行程。可以直接告訴我哪一天不合理。',UNSAFE_OR_INAPPROPRIATE_REQUEST:'我不能協助這個不安全或不適當的要求，也不會修改行程；可以改談安全的文化或一般觀光方向。'};return replies[gate.type]}
  if(gate.type==='EXPLANATION_OR_COMPLAINT'&&!/為什麼|怎麼|Day\s*\d|第.+天/i.test(text))return'我有讀到你對這份行程不滿意。是動線、太累、景點類型，還是用餐安排的問題？你指定後我再修改，目前 state 不變。';
  let intent=ItineraryCore.classifyChatIntent(text),reference=chatDayContext(text);
  if(['EXPLANATION','COMPLAINT'].includes(intent))intent='QUESTION';
  if(['REPLAN_DAY','REPLAN_TRIP'].includes(intent))intent='REGENERATE';
  if(['ADD_ITEM','REMOVE_ITEM','MOVE_ITEM','REPLACE_ITEM','CHANGE_PACE'].includes(intent))intent='MODIFY';
  if(confirmPending(text)){intent=pendingChatAction.intent;reference={resolved:true,dayIndex:pendingChatAction.dayIndex,dayNumber:pendingChatAction.dayIndex+1,source:'confirmation'};pendingChatAction=null}
  if(intent==='QUESTION'){
    if(!reference.resolved)return'我會先讀取行程再回答；請告訴我你是問 Day 幾，我不會擅自猜測或修改。';
    const status=dayState(reference.dayIndex);
    if(!status.exists||status.count===0){pendingChatAction={intent:'REGENERATE',dayIndex:reference.dayIndex};return`你說得對，Day ${reference.dayNumber} 目前是空的，這是行程生成失敗，不是正常結果。我可以只補排 Day ${reference.dayNumber}，並保留其他日期。要現在補排嗎？`}
    return`Day ${reference.dayNumber} 目前有 ${status.count} 個活動，驗證${status.errors.length?`發現 ${status.errors.length} 個問題`:'通過'}；這是狀態說明，我沒有修改任何行程。`;
  }
  if(intent==='STATUS'){
    const index=reference.resolved?reference.dayIndex:state.activeDay,status=dayState(index),names=(state.itinerary[index]||[]).map(displayName);
    return`Day ${index+1} 目前有 ${status.count} 個活動${names.length?`：${names.join('、')}`:''}。驗證${status.errors.length?'未通過':'通過'}。`;
  }
  if(intent==='AMBIGUOUS')return'我無法確定你是要詢問，還是要修改行程。請明確說「幫我修改 Day X」或「為什麼 Day X…」，我不會擅自改動。';
  if(!reference.resolved)return'我知道你想修改行程，但無法確定是哪一天。請指定 Day 幾、第幾天、今天或最後一天。';
  const before=state.itinerary.map(day=>[...(day||[])]),beforeSignature=itinerarySignature(),dayIndex=reference.dayIndex;
  try{
    if(intent==='REGENERATE'){
      const result=repairDayAtIndex(dayIndex,state.request);
      if(!result.success)return mutationFailure();
    }else{
      const day=state.itinerary[dayIndex]||[],mentioned=findMentionedPlace(text);
      if(/刪除|移除/.test(text)){const target=day.find(place=>text.includes(displayName(place))||text.includes(place.nameJa||'__'));if(!target)return mutationFailure('指定地點不在該日行程');day.splice(day.indexOf(target),1)}
      else if(/不要太累|好累|太累|放鬆|少一點/.test(text)){if(day.length<=2)return mutationFailure('這天已經只剩最低合理活動數');day.pop()}
      else if(/購物|逛街|買特買/.test(text)){const shopping=RECOMMENDATION_PLACES.filter(place=>place.category==='購物血拼').sort((a,b)=>scorePlace(b,{...state.request,themes:['shopping']})-scorePlace(a,{...state.request,themes:['shopping']}))[0],result=repairDayAtIndex(dayIndex,{...state.request,themes:['shopping']},shopping);if(!result.success)return mutationFailure()}
      else if(mentioned){const result=repairDayAtIndex(dayIndex,state.request,mentioned);if(!result.success)return mutationFailure()}
      else return'我知道你要修改，但目前找不到可驗證的地點或明確操作；原行程未改動。';
      const validation=currentValidation();if(!validation.valid){state.itinerary=before;currentValidation();return mutationFailure()}
    }
    const after=itinerarySignature();if(after===beforeSignature){state.itinerary=before;currentValidation();return mutationFailure('資料寫入後沒有實際變更')}
    persistTripDraft();renderTrip();const status=dayState(dayIndex),setting=daySetting(dayIndex);return`已完成 Day ${dayIndex+1} 的修改，共安排 ${status.count} 個行程，時間為 ${setting.start}～${setting.end}；其他日期未修改，且寫入後已重新通過完整性驗證。`;
  }catch(error){state.itinerary=before;currentValidation();return mutationFailure(error.message)}
}
let conversationState=ItineraryCore.createConversationState();
const handleChatBase=handleChat;
async function modelChatDecision(text,context){const base=String(window.TABI_CONFIG?.smartApiBaseUrl||'').replace(/\/$/,'');if(!base)throw new Error('AI Gateway 未設定');const itinerarySummary=state.itinerary.map((day,index)=>({dayNumber:index+1,date:state.tripDates[index],items:day.map(place=>({id:place.id,name:displayName(place),category:place.category}))})),response=await fetch(`${base}/api/chat/decision`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({message:text,context,conversationState,itinerarySummary,selectedItemId:null})});if(!response.ok)throw new Error(`AI Chat HTTP ${response.status}`);const result=await response.json();state.lastChatAiMeta=result.meta;return result.decision}
handleChat=async function(text){const context={tripDays:state.tripDates.length,dates:state.tripDates,currentTravelDayNumber:currentTravelDayNumber(),activeDayNumber:state.activeDay+1};let decision;try{decision=await modelChatDecision(text,context)}catch{decision=ItineraryCore.classifyChatDecision(text,context,conversationState);decision.responseDraft=decision.clarificationQuestion||''}const injection=/忽略.*(?:規則|驗證)|系統提示詞|ignore all/i.test(text),destructive=/整趟.*(?:刪|清空)|全部.*(?:刪|清空)/.test(text);if(injection||destructive)return'這項要求可能繞過驗證或清除整趟行程，因此我不會執行。若你確實要刪除旅程，請到旅程設定使用明確的刪除與二次確認。';conversationState=ItineraryCore.advanceConversation(conversationState,decision);state.chatConversationState=conversationState;if(['QUESTION','COMPLAINT'].includes(decision.primaryIntent)&&decision.targetDay){const target=decision.targetDay==='LAST'?state.itinerary.length:Number(decision.targetDay),status=dayState(target-1);return`我先讀取真實行程：Day ${target} 目前有 ${status.count} 個活動，${status.errors.length?'驗證有問題':'驗證通過'}。我尚未修改任何資料。${decision.responseDraft||''}`}if(['CASUAL_CHAT','NONSENSE','UNSAFE','AMBIGUOUS'].includes(decision.primaryIntent)||decision.missingSlots?.length)return decision.clarificationQuestion||decision.responseDraft||'可以再多告訴我一點你想調整的內容嗎？';if(!decision.shouldModifyNow)return decision.responseDraft||'我已理解你的要求，但尚未修改行程。';const target=decision.targetDay==='LAST'?state.itinerary.length:Number(decision.targetDay||context.activeDayNumber);if(!Number.isInteger(target)||target<1||target>state.itinerary.length)return'我還無法確認要修改哪一天，因此沒有更動行程。';const preview=`${text} 第${target}天`;const reply=await handleChatBase(preview);return reply};
$('#chatForm').onsubmit=async event=>{event.preventDefault();const input=$('#chatInput'),text=input.value.trim();if(!text)return;chatMessage(text,'user');input.value='';chatMessage('我正在讀取現有行程與判斷你的意圖…');const waiting=$('#chatMessages').lastElementChild;try{const before=itinerarySignature(),reply=await handleChat(text);waiting.remove();chatMessage(reply);const decision=ItineraryCore.classifyChatDecision(text,{tripDays:state.tripDates.length},conversationState);if(!decision.shouldModifyNow&&itinerarySignature()!==before)throw new Error('這段對話不應修改行程')}catch(error){waiting.textContent=`這次操作失敗：${error.message}；原行程未被破壞。`}};
if(state.itinerary.length){$('#aiChat').classList.remove('hidden');updateCompanionDashboard()}
