let pendingUnderstanding=null,dayRouteMap=null,dayRouteLayer=null;
const completedStops=new Set(JSON.parse(localStorage.getItem('tabi-completed-stops')||'[]'));
const companionMemory=JSON.parse(localStorage.getItem('tabi-companion-memory')||'{"trips":[]}');
const themeLabels={food:'美食',shopping:'購物',shrine:'寺社／御朱印',anime:'動漫',nature:'自然',night:'夜景',family:'親子／樂園',classic:'經典景點'};
function saveCompleted(){localStorage.setItem('tabi-completed-stops',JSON.stringify([...completedStops]));saveCompanionMemory()}
function saveCompanionMemory(){if(!state.tripDates?.length||!state.itinerary?.length)return;const tripId=`${state.tripDates[0]}::${state.tripDates.at(-1)}`,all=state.itinerary.flat(),done=all.filter(p=>state.tripDates.some(date=>completedStops.has(`${date}::${p.id}`))),record={id:tripId,start:state.tripDates[0],end:state.tripDates.at(-1),completedCount:done.length,religiousCount:done.filter(p=>p.category==='神社寺廟').length,updatedAt:new Date().toISOString()};const index=companionMemory.trips.findIndex(x=>x.id===tripId);index>=0?companionMemory.trips[index]=record:companionMemory.trips.push(record);companionMemory.trips=companionMemory.trips.slice(-20);localStorage.setItem('tabi-companion-memory',JSON.stringify(companionMemory))}
function memoryText(){const trips=companionMemory.trips||[];if(!trips.length)return'這是本裝置的第一趟旅程';const last=trips[trips.length-1];return`本裝置記得 ${trips.length} 趟旅程；最近一次完成 ${last.completedCount||0} 個地點${last.religiousCount?`、寺社 ${last.religiousCount} 間`:''}`}
function understandingHtml(request){const days=dateRange($('#tripStartDate').value,$('#tripEndDate').value).length,party=[...state.party].map(x=>({adult:'一般成人',elderly:'長者',child:'兒童',stroller:'嬰兒車'}[x])).join('、'),religious=request.religiousMode==='temple_only'?'只安排寺廟，排除神社':request.religiousMode==='shrine_only'?'只安排神社，排除寺廟':'寺廟與神社皆可',constraints=(request.travelRequirements?.dayConstraints||[]).map(item=>item.source).join('、')||'無';return`<dl><div><dt>旅行日期</dt><dd>${$('#tripStartDate').value}～${$('#tripEndDate').value}（${days}天）</dd></div><div><dt>每天時間</dt><dd>${request.clock.start}～${request.clock.end}</dd></div><div><dt>特定日限制</dt><dd>${constraints}</dd></div><div><dt>偏好</dt><dd>${request.themes.map(x=>themeLabels[x]||x).join('、')||'由AI依經典行程補足'}</dd></div><div><dt>寺社條件</dt><dd>${religious}</dd></div><div><dt>同行者</dt><dd>${party||'一般成人'}</dd></div><div><dt>每日預算</dt><dd>約 ¥${Number($('#budget').value).toLocaleString()}</dd></div><div><dt>指定天數</dt><dd>美食 ${request.dayQuotas?.food||0} 天・樂園 ${request.dayQuotas?.amusement||0} 天・夜景 ${request.dayQuotas?.night||0} 天</dd></div><div><dt>旅程記憶</dt><dd>${memoryText()}（目前只存在這台裝置）</dd></div><div><dt>AI解析</dt><dd>${request.parserSource||'AI Travel Companion'}</dd></div></dl>`}
function inputGateContext(){const dates=dateRange($('#tripStartDate').value,$('#tripEndDate').value);return{defaultDestination:'東京',tripDays:dates.length,dates:{start:dates[0]||null,end:dates.at(-1)||null},hasItinerary:false}}
const understandingHtmlBase=understandingHtml;
understandingHtml=function(request){const base=understandingHtmlBase(request),requirements=request.travelRequirements,tracked=[...(requirements?.dayConstraints||[]).map(item=>item.source),...(requirements?.frequencyRequirements||[]).map(item=>item.source)],sourceLabels={USER_FORM:'依你最後手動設定',USER_TEXT:'依文字描述',AI_EXTRACTED:'AI 抽取',DEFAULT:'預設值'},fields=state.normalizedTripRequirements.fields,conflicts=state.normalizedTripRequirements.conflicts||[],fieldSummary=`步調：${fields.pace?.value}（${sourceLabels[fields.pace?.source]}）・同行者：${(fields.party?.value||[]).join('、')}（${sourceLabels[fields.party?.source]}）・時間：${fields.startTime?.value}～${fields.endTime?.value}`;const conflictHtml=conflicts.length?`<section class="requirement-conflicts"><h3>偵測到 ${conflicts.length} 項設定不同</h3>${conflicts.map((item,index)=>`<div data-conflict="${index}"><p>文字描述：${escapeGuideText(String(item.textValue))}<br>目前選項：${escapeGuideText(String(item.formValue))}</p><button type="button" data-resolve-conflict="${index}:TEXT">以文字為準</button><button type="button" data-resolve-conflict="${index}:FORM">以目前選項為準</button><button type="button" data-resolve-conflict="${index}:COMPROMISE">讓 AI 折衷</button></div>`).join('')}</section>`:'';return base.replace('</dl>',`<div><dt>統一需求狀態</dt><dd>${escapeGuideText(fieldSummary)}</dd></div><div><dt>必須驗證的需求</dt><dd>${tracked.length?tracked.map(escapeGuideText).join('、'):'無'}</dd></div></dl>${conflictHtml}`)};
function bindConflictControls(){$$('[data-resolve-conflict]').forEach(button=>button.onclick=()=>{const[index,choice]=button.dataset.resolveConflict.split(':'),conflict=state.normalizedTripRequirements.conflicts[Number(index)];TripRequirementsState.resolve(state.normalizedTripRequirements,Number(index),choice);if(choice!=='FORM')state.manualRequirementFields.delete(conflict.field);saveNormalizedRequirements();const section=button.closest('[data-conflict]');section.innerHTML=`<p>已選擇：${choice==='TEXT'?'以文字描述為準':choice==='FORM'?'以目前選項為準':'使用折衷設定'}</p>`;syncFormFromRequirements()})}
function showInputGate(classification){const messages={NONSENSE_OR_GIBBERISH:'我目前無法理解這段內容。你可以告訴我目的地、天數和想做的事情。',VALID_BUT_INCOMPLETE:'這是旅遊需求，但還缺目的地或天數，補充後我再幫你排。',TRAVEL_QUESTION:'這是旅遊問題，不是排行程指令；我不會因此覆蓋現有行程。',OFF_TOPIC:'謝謝你。我會專心當你的日本旅遊夥伴；想規劃時，告訴我地點、天數和偏好就好。',ABUSIVE_LANGUAGE:'我不會和你對罵，也不會因這段話亂改行程。如果願意，請重新描述旅行需求。',UNSAFE_OR_INAPPROPRIATE_REQUEST:'我不能協助這個不安全或不適當的要求，也不會生成相關路線。我可以改為安全的動漫文化、商圈或一般觀光行程。',AMBIGUOUS:'我不確定你想詢問還是規劃行程，請再多說一句，我不會擅自猜測。'};const box=$('#plannerValidationError');box.innerHTML=`<b>先確認一下你的需求</b><p>${messages[classification.type]||classification.reason}</p>`;box.classList.remove('hidden')}
async function startCompanionPlanning(){const raw=$('#tripPrompt').value,classification=TravelQuality.classifyInput(raw,inputGateContext());state.lastInputClassification=classification;if(classification.type!=='VALID_TRAVEL_REQUEST'){showInputGate(classification);return}clearPlannerValidationError();const overlay=$('#loadingOverlay');overlay.classList.remove('hidden');$('#loadingText').textContent='AI 正在整理你的旅行需求…';try{pendingUnderstanding=await smartParseRequest(raw);pendingUnderstanding.travelRequirements=classification.requirements;pendingUnderstanding.inputClassification=classification;const constraints=classification.requirements.dayConstraints||[],everyStart=constraints.find(item=>item.dayNumber==='EVERY'&&item.type==='EARLIEST_START'),everyEnd=constraints.find(item=>item.dayNumber==='EVERY'&&item.type==='LATEST_END'),extracted={pace:classification.requirements.pace,startTime:everyStart?.value||pendingUnderstanding.clock?.start,endTime:everyEnd?.value||pendingUnderstanding.clock?.end,party:[...(classification.requirements.travelers.seniors.length?['elderly']:[]),...(classification.requirements.travelers.children.length?['child']:[])]};state.normalizedTripRequirements=TripRequirementsState.merge({base:state.normalizedTripRequirements,rawText:raw,extracted,form:requirementsFormSnapshot(),manualFields:[...state.manualRequirementFields]});syncFormFromRequirements();saveNormalizedRequirements();const unified=TripRequirementsState.plain(state.normalizedTripRequirements);pendingUnderstanding.normalizedTripRequirements=unified;pendingUnderstanding.clock={start:unified.startTime,end:unified.endTime};state.pace={LEISURELY:'leisurely',BALANCED:'balanced',INTENSIVE:'intensive'}[unified.pace]||state.pace;state.party=new Set(unified.party?.length?unified.party:['adult']);if(classification.requirements.collectionGoals.includes('東京十社')){const series=PILGRIMAGE_SERIES.find(item=>item.id==='tokyo-jissha'),ids=(series?.stops||[]).map(findPlaceForStop).filter(Boolean).map(place=>place.id);pendingUnderstanding.musts=[...new Set([...(pendingUnderstanding.musts||[]),...ids])]}$('#aiUnderstanding').innerHTML=understandingHtml(pendingUnderstanding);bindConflictControls();$('#aiConfirmModal').classList.remove('hidden');document.body.style.overflow='hidden'}finally{overlay.classList.add('hidden')}}
const startCompanionPlanningBase=startCompanionPlanning;
startCompanionPlanning=async function(){const classification=TravelQuality.classifyInput($('#tripPrompt').value,inputGateContext()),capability=classification.type==='VALID_TRAVEL_REQUEST'?TravelQuality.checkProductCapability(classification.requirements,['東京']):{supported:true,unsupported:[]};if(!capability.supported){showInputGate({type:'AMBIGUOUS'});$('#plannerValidationError p').textContent=`目前試作版只支援東京，不能假裝已規劃 ${capability.unsupported.join('、')}；請改選東京，其他城市已放入後續版本。`;return}return startCompanionPlanningBase()};
$('#editUnderstanding').onclick=()=>{$('#aiConfirmModal').classList.add('hidden');document.body.style.overflow=''};
$('#confirmUnderstanding').onclick=async()=>{const unresolved=TripRequirementsState.unresolved(state.normalizedTripRequirements);if(unresolved.length){const box=$('#plannerValidationError');box.innerHTML=`<b>請先解決 ${unresolved.length} 項需求衝突</b><p>我不會在文字描述與表單設定不同時靜默猜測。</p>`;box.classList.remove('hidden');return}$('#aiConfirmModal').classList.add('hidden');document.body.style.overflow='';const overlay=$('#loadingOverlay'),steps=['整合你指定的景點與收藏目標…','依區域分組，避免跨區折返…','檢查寺務所／社務所與營業時間…','安排交通、用餐與休息緩衝…','完成每日節奏與可編輯草稿…'];overlay.classList.remove('hidden');let index=0;$('#loadingText').textContent=steps[0];const timer=setInterval(()=>{$('#loadingText').textContent=steps[Math.min(++index,steps.length-1)]},650),originalSmart=smartParseRequest;smartParseRequest=async()=>pendingUnderstanding;try{const success=await generateItinerary();if(success){$('#aiChat').classList.remove('hidden');updateCompanionDashboard()}}finally{smartParseRequest=originalSmart;clearInterval(timer);overlay.classList.add('hidden')}};
function stopKey(dayIndex,placeId){return`${state.tripDates[dayIndex]}::${placeId}`}
function updateCompanionDashboard(){if(!state.itinerary.length)return;const day=state.itinerary[state.activeDay]||[],done=day.filter(p=>completedStops.has(stopKey(state.activeDay,p.id))).length,percent=day.length?Math.round(done/day.length*100):0;$('#todayCompletion').textContent=`${percent}%`;$('#companionGreeting').textContent=percent===100?'今天的旅程完成了，辛苦了！':new Date().getHours()<12?'早安，今天一起好好旅行。':'我還在，接下來也陪你走。';const steps=Number($('#todaySteps').value)||0;$('#todayAdvice').textContent=steps>=20000?'今天步數很高，建議先補水並休息20分鐘。':steps>=10000?'已走不少路，下一站前找地方坐一下吧。':`今天還有 ${Math.max(0,day.length-done)} 個地點，按自己的節奏前進。`;enhanceStopCards()}
function enhanceStopCards(){$$('.editable-stop').forEach(card=>{const index=Number(card.dataset.stopIndex),place=state.itinerary[state.activeDay]?.[index];if(!place||card.querySelector('.complete-stop'))return;const button=document.createElement('button');button.className='complete-stop';const key=stopKey(state.activeDay,place.id);button.textContent=completedStops.has(key)?'✓ 已完成':'○ 標示完成';button.onclick=()=>{completedStops.has(key)?completedStops.delete(key):completedStops.add(key);saveCompleted();updateCompanionDashboard()};card.querySelector('.stop-edit-actions')?.append(button)})}
const originalRenderDay=renderDay;renderDay=function(){originalRenderDay();updateCompanionDashboard()};
$('#todaySteps').oninput=()=>{localStorage.setItem('tabi-today-steps',$('#todaySteps').value);updateCompanionDashboard()};$('#todaySteps').value=localStorage.getItem('tabi-today-steps')||0;
async function refreshWeather(){const day=state.itinerary[state.activeDay]||[],center=day[0]||{lat:35.6812,lng:139.7671};$('#todayWeather').textContent='更新中…';try{const response=await fetch(`https://api.open-meteo.com/v1/forecast?latitude=${center.lat}&longitude=${center.lng}&current=temperature_2m,precipitation,weather_code&timezone=Asia%2FTokyo`),data=await response.json(),current=data.current;$('#todayWeather').textContent=`${Math.round(current.temperature_2m)}°C・降雨 ${current.precipitation}mm`;if(current.precipitation>0)$('#todayAdvice').textContent='目前可能下雨，建議優先室內景點；可在聊天室要求我重新安排。'}catch{$('#todayWeather').textContent='天氣暫時無法取得'}}
$('#weatherCard').onclick=refreshWeather;
$('#replanToday').onclick=async()=>{const day=state.itinerary[state.activeDay]||[];if(!day.length)return;$('#aiChat').classList.remove('hidden');$('#aiChat').classList.add('open');chatMessage('請依照今天的體力與天氣重新安排，但保留已完成地點。','user');const steps=Number($('#todaySteps').value)||0,unfinished=day.filter(p=>!completedStops.has(stopKey(state.activeDay,p.id)));if(steps>=15000&&unfinished.length>1){const removed=unfinished.at(-1);day.splice(day.indexOf(removed),1);renderTrip();persistTripState();chatMessage(`你今天已走 ${steps.toLocaleString()} 步，我先移除最後一站「${displayName(removed)}」，保留已完成地點並讓行程提早結束。`);return}await refreshWeather();chatMessage('我已保留既有行程與完成紀錄。若要更精準調整，直接告訴我「下雨改室內」、「減少一站」或想加入的類型。')};
function routeLegText(from,to){const leg=estimateTransportLeg(from,to);return`${leg.mode}約 ${leg.minutes} 分鐘${leg.fare?`・約 ¥${leg.fare}`:''}`}
function showTodayRoute(){const day=state.itinerary[state.activeDay]||[];if(!day.length)return;$('#dayRouteTitle').textContent=`${state.tripDates[state.activeDay]} 今日動線`;$('#dayRouteModal').classList.remove('hidden');document.body.style.overflow='hidden';setTimeout(()=>{if(!dayRouteMap)dayRouteMap=L.map('dayRouteMap').setView([day[0].lat,day[0].lng],12);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'&copy; OpenStreetMap'}).addTo(dayRouteMap);if(dayRouteLayer)dayRouteLayer.remove();dayRouteLayer=L.layerGroup().addTo(dayRouteMap);const points=day.map(p=>[p.lat,p.lng]);day.forEach((p,i)=>L.marker(points[i],{icon:L.divIcon({className:'route-number-icon',html:`<span>${i+1}</span>`,iconSize:[30,30]})}).addTo(dayRouteLayer).bindPopup(displayName(p)));L.polyline(points,{color:'#e76e46',weight:5,dashArray:'8 7'}).addTo(dayRouteLayer);dayRouteMap.fitBounds(points,{padding:[28,28]});dayRouteMap.invalidateSize();$('#dayRouteLegs').innerHTML=day.slice(1).map((p,i)=>`<div><b>${i+1} → ${i+2}</b><span>${routeLegText(day[i],p)}</span></div>`).join('')},80)}
$('#showDayRoute').onclick=showTodayRoute;$('#closeDayRoute').onclick=closeTodayRoute;$('[data-close-route]').onclick=closeTodayRoute;function closeTodayRoute(){$('#dayRouteModal').classList.add('hidden');document.body.style.overflow=''}
$('#startTodayTrip').onclick=()=>{const day=state.itinerary[state.activeDay]||[],next=day.find(p=>!completedStops.has(stopKey(state.activeDay,p.id)))||day[0];if(!next)return;const apple=/iPhone|iPad|Mac/.test(navigator.userAgent),url=apple?`https://maps.apple.com/?daddr=${next.lat},${next.lng}&dirflg=r`:`https://www.google.com/maps/dir/?api=1&destination=${next.lat},${next.lng}&travelmode=transit`;window.open(url,'_blank','noopener')};
function makeDiary(){const day=state.itinerary[state.activeDay]||[],done=day.filter(p=>completedStops.has(stopKey(state.activeDay,p.id))),steps=Number($('#todaySteps').value)||0,goshuin=done.filter(p=>p.category==='神社寺廟').length,metrics=dayMetrics(day);const text=`${state.tripDates[state.activeDay]}，今天走了約 ${steps.toLocaleString()} 步，完成 ${done.length}/${day.length} 個地點${done.length?`：${done.map(displayName).join('、')}`:''}。${goshuin?`寺社參拜 ${goshuin} 間，也替收藏旅程留下新的進度。`:''}今日基本花費估算約 ¥${metrics.cost.toLocaleString()}。旅程不必追求全部打卡，能按自己的節奏留下記憶，就是很好的一天。`;$('#travelDiary').innerHTML=`<h3>AI 今日旅行日記</h3><p>${escapeGuideText(text)}</p>`;$('#travelDiary').classList.remove('hidden');saveCompanionMemory();return text}
$('#makeDiary').onclick=makeDiary;$('#shareToday').onclick=async()=>{const text=makeDiary();if(navigator.share)await navigator.share({title:'我的日本旅行日記',text,url:location.href}).catch(()=>{});else{await navigator.clipboard.writeText(text);alert('旅行摘要已複製，可貼到 LINE、Threads 或 IG。')}};
$('#toggleChat').onclick=()=>$('#aiChat').classList.toggle('open');$('#closeChat').onclick=()=>$('#aiChat').classList.remove('open');
function chatMessage(text,role='ai'){const p=document.createElement('p');p.className=role==='user'?'user-message':'ai-message';p.textContent=text;$('#chatMessages').append(p);p.scrollIntoView({behavior:'smooth',block:'end'})}
let pendingChatAction=null;
function currentTravelDayNumber(){const today=todayLocal(),index=state.tripDates.indexOf(today);return index>=0?index+1:state.activeDay+1}
function chatDayContext(text){return ItineraryCore.resolveDayReference(text,{tripDays:state.tripDates.length,dates:state.tripDates,currentTravelDayNumber:currentTravelDayNumber(),activeDayNumber:state.activeDay+1})}
function itinerarySignature(){return JSON.stringify(state.itinerary.map(day=>(day||[]).map(place=>place.id)))}
function dayState(dayIndex){const day=state.itinerary[dayIndex],validation=currentValidation(),errors=validation.errors.filter(error=>error.dayNumber===dayIndex+1);return{exists:Array.isArray(day),count:Array.isArray(day)?day.length:0,dayType:state.structuredItinerary?.days?.[dayIndex]?.dayType||'full',errors,rendered:dayIndex!==state.activeDay||$$('.editable-stop').length===(day?.length||0)}}
function findMentionedPlace(text){return RECOMMENDATION_PLACES.find(place=>text.includes(displayName(place))||text.includes(place.nameJa||'__')||text.includes(place.nameEn||'__'))}
function confirmPending(text){return pendingChatAction&&/^(?:好|好的|是|可以|現在|幫我|開始|確定)/.test(text)}
function mutationFailure(reason='修改後的行程未通過完整性驗證'){return`這次修改失敗：${reason}；原行程已保留，我不會假裝已完成。`}
async function handleChat(text){
  const gate=TravelQuality.classifyInput(text,{hasItinerary:true});
  if(['NONSENSE_OR_GIBBERISH','OFF_TOPIC','ABUSIVE_LANGUAGE','UNSAFE_OR_INAPPROPRIATE_REQUEST'].includes(gate.type)){const replies={NONSENSE_OR_GIBBERISH:'我目前無法理解這段內容；請改說要調整哪一天與什麼內容，原行程未改動。',OFF_TOPIC:'謝謝你。我會留在這裡陪你處理旅行；原行程沒有改動。',ABUSIVE_LANGUAGE:'我不會和你對罵，也不會亂改行程。可以直接告訴我哪一天不合理。',UNSAFE_OR_INAPPROPRIATE_REQUEST:'我不能協助這個不安全或不適當的要求，也不會修改行程；可以改談安全的文化或一般觀光方向。'};return replies[gate.type]}
  if(gate.type==='EXPLANATION_OR_COMPLAINT'&&!/為什麼|怎麼|Day\s*\d|第.+天/i.test(text))return'我有讀到你對這份行程不滿意。是動線、太累、景點類型，還是用餐安排的問題？你指定後我再修改，目前 state 不變。';
  let intent=ItineraryCore.classifyChatIntent(text),reference=chatDayContext(text);
  if(['EXPLANATION','COMPLAINT'].includes(intent))intent='QUESTION';
  if(['REPLAN_DAY','REPLAN_TRIP'].includes(intent))intent='REGENERATE';
  if(['ADD_ITEM','REMOVE_ITEM','MOVE_ITEM','REPLACE_ITEM','CHANGE_PACE'].includes(intent))intent='MODIFY';
  if(confirmPending(text)){intent=pendingChatAction.intent;reference={resolved:true,dayIndex:pendingChatAction.dayIndex,dayNumber:pendingChatAction.dayIndex+1,source:'confirmation'};pendingChatAction=null}
  if(intent==='QUESTION'){
    if(!reference.resolved)return'我會先讀取行程再回答；請告訴我你是問 Day 幾，我不會擅自猜測或修改。';
    const status=dayState(reference.dayIndex);
    if(!status.exists||status.count===0){pendingChatAction={intent:'REGENERATE',dayIndex:reference.dayIndex};return`你說得對，Day ${reference.dayNumber} 目前是空的，這是行程生成失敗，不是正常結果。我可以只補排 Day ${reference.dayNumber}，並保留其他日期。要現在補排嗎？`}
    return`Day ${reference.dayNumber} 目前有 ${status.count} 個活動，驗證${status.errors.length?`發現 ${status.errors.length} 個問題`:'通過'}；這是狀態說明，我沒有修改任何行程。`;
  }
  if(intent==='STATUS'){
    const index=reference.resolved?reference.dayIndex:state.activeDay,status=dayState(index),names=(state.itinerary[index]||[]).map(displayName);
    return`Day ${index+1} 目前有 ${status.count} 個活動${names.length?`：${names.join('、')}`:''}。驗證${status.errors.length?'未通過':'通過'}。`;
  }
  if(intent==='AMBIGUOUS')return'我無法確定你是要詢問，還是要修改行程。請明確說「幫我修改 Day X」或「為什麼 Day X…」，我不會擅自改動。';
  if(!reference.resolved)return'我知道你想修改行程，但無法確定是哪一天。請指定 Day 幾、第幾天、今天或最後一天。';
  const before=state.itinerary.map(day=>[...(day||[])]),beforeSignature=itinerarySignature(),dayIndex=reference.dayIndex;
  try{
    if(intent==='REGENERATE'){
      const result=repairDayAtIndex(dayIndex,state.request);
      if(!result.success)return mutationFailure();
    }else{
      const day=state.itinerary[dayIndex]||[],mentioned=findMentionedPlace(text);
      if(/刪除|移除/.test(text)){const target=day.find(place=>text.includes(displayName(place))||text.includes(place.nameJa||'__'));if(!target)return mutationFailure('指定地點不在該日行程');day.splice(day.indexOf(target),1)}
      else if(/不要太累|好累|太累|放鬆|少一點/.test(text)){if(day.length<=2)return mutationFailure('這天已經只剩最低合理活動數');day.pop()}
      else if(/購物|逛街|買特買/.test(text)){const shopping=RECOMMENDATION_PLACES.filter(place=>place.category==='購物血拼').sort((a,b)=>scorePlace(b,{...state.request,themes:['shopping']})-scorePlace(a,{...state.request,themes:['shopping']}))[0],result=repairDayAtIndex(dayIndex,{...state.request,themes:['shopping']},shopping);if(!result.success)return mutationFailure()}
      else if(mentioned){const result=repairDayAtIndex(dayIndex,state.request,mentioned);if(!result.success)return mutationFailure()}
      else return'我知道你要修改，但目前找不到可驗證的地點或明確操作；原行程未改動。';
      const validation=currentValidation();if(!validation.valid){state.itinerary=before;currentValidation();return mutationFailure()}
    }
    const after=itinerarySignature();if(after===beforeSignature){state.itinerary=before;currentValidation();return mutationFailure('資料寫入後沒有實際變更')}
    persistTripDraft();renderTrip();const status=dayState(dayIndex),setting=daySetting(dayIndex);return`已完成 Day ${dayIndex+1} 的修改，共安排 ${status.count} 個行程，時間為 ${setting.start}～${setting.end}；其他日期未修改，且寫入後已重新通過完整性驗證。`;
  }catch(error){state.itinerary=before;currentValidation();return mutationFailure(error.message)}
}
let conversationState=ItineraryCore.createConversationState();
const handleChatBase=handleChat;
handleChat=async function(text){const context={tripDays:state.tripDates.length,dates:state.tripDates,currentTravelDayNumber:currentTravelDayNumber(),activeDayNumber:state.activeDay+1},decision=ItineraryCore.classifyChatDecision(text,context,conversationState);conversationState=ItineraryCore.advanceConversation(conversationState,decision);state.chatConversationState=conversationState;if(decision.primaryIntent==='EXPRESS_FRUSTRATION')return decision.clarificationQuestion;if(decision.primaryIntent==='CASUAL_CHAT')return'謝謝你。我會繼續陪你把這趟日本旅行調整好；目前行程沒有改動。';if(decision.primaryIntent==='NONSENSE')return decision.clarificationQuestion;if(decision.primaryIntent==='COMPLAINT'&&decision.secondaryIntent==='ASK_QUESTION'&&decision.targetDay){const status=dayState(decision.targetDay-1);return`你說得對，我先確認現況：Day ${decision.targetDay} 目前有 ${status.count} 個活動，${status.errors.length?'驗證有問題':'驗證通過'}。我沒有擅自修改；如果要修，我可以只處理這一天。`}if(decision.shouldAskClarification)return decision.clarificationQuestion;if(decision.primaryIntent==='MODIFY_ITINERARY'&&decision.shouldModifyNow){const enriched=`${text} 第${decision.targetDay}天`;conversationState=ItineraryCore.createConversationState();state.chatConversationState=conversationState;return handleChatBase(enriched)}return handleChatBase(text)};
$('#chatForm').onsubmit=async event=>{event.preventDefault();const input=$('#chatInput'),text=input.value.trim();if(!text)return;chatMessage(text,'user');input.value='';chatMessage('我正在讀取現有行程與判斷你的意圖…');const waiting=$('#chatMessages').lastElementChild;try{const before=itinerarySignature(),reply=await handleChat(text);waiting.remove();chatMessage(reply);const decision=ItineraryCore.classifyChatDecision(text,{tripDays:state.tripDates.length},conversationState);if(!decision.shouldModifyNow&&itinerarySignature()!==before)throw new Error('這段對話不應修改行程')}catch(error){waiting.textContent=`這次操作失敗：${error.message}；原行程未被破壞。`}};
if(state.itinerary.length){$('#aiChat').classList.remove('hidden');updateCompanionDashboard()}
