(function(root,factory){const api=factory(typeof require==='function'?require('./planning-policy.js'):root.PlanningPolicy);if(typeof module==='object'&&module.exports)module.exports=api;else root.PlannerEngine=api})(typeof globalThis!=='undefined'?globalThis:this,function(Policy){
  const isMeal=place=>/(餐廳|美食|咖啡)/.test(`${place.category||''}${place.kind||''}`),isRest=place=>/(休息|咖啡|公園)/.test(`${place.category||''}${place.kind||''}`),isReligious=place=>place.category==='神社寺廟';
  const km=(a,b)=>{if(!a||!b||!Number.isFinite(a.lat)||!Number.isFinite(b.lat))return 1;const r=6371,dLat=(b.lat-a.lat)*Math.PI/180,dLon=(b.lng-a.lng)*Math.PI/180,x=Math.sin(dLat/2)**2+Math.cos(a.lat*Math.PI/180)*Math.cos(b.lat*Math.PI/180)*Math.sin(dLon/2)**2;return r*2*Math.atan2(Math.sqrt(x),Math.sqrt(1-x))};
  function resolveEntities(requirements,places){const aliases=new Map();for(const place of places)for(const value of [place.id,place.name,place.nameJa,place.nameEn,...(place.aliases||[])])if(value)aliases.set(String(value).trim().toLocaleLowerCase(),place.id);return(requirements.requirements||[]).map(req=>({...req,resolvedPlaceId:req.resolvedPlaceId||aliases.get(String(req.value).trim().toLocaleLowerCase())||null}))}
  function score(place,requirements,entities){let value=Number(place.popularity||0);const must=entities.some(req=>req.resolvedPlaceId===place.id&&req.priority==='MUST');if(must)value+=10000;for(const interest of requirements.interests||[])if(`${place.category} ${(place.tags||[]).join(' ')}`.toLocaleLowerCase().includes(String(interest).toLocaleLowerCase()))value+=200;return value}
  function selectCandidates(requirements,places){const entities=resolveEntities(requirements,places),ranked=places.slice().sort((a,b)=>score(b,requirements,entities)-score(a,requirements,entities));return{entities,candidates:ranked}}
  function group(candidates,tripDays,minimum=2){const groups=Array.from({length:tripDays},()=>[]),zones=new Map();for(const place of candidates){if(!zones.has(place.zone))zones.set(place.zone,[]);zones.get(place.zone).push(place)}const ordered=[...zones.values()].sort((a,b)=>Math.max(...b.map(x=>x.popularity||0))-Math.max(...a.map(x=>x.popularity||0)));ordered.forEach((places,index)=>groups[index%tripDays].push(...places));for(const target of groups)while(target.length<minimum){const donor=groups.filter(group=>group!==target).sort((a,b)=>b.length-a.length)[0];if(!donor||donor.length<=minimum)break;target.push(donor.pop())}return groups}
  function schedule(requirements,dates,groups,entities,policy){const used=new Set();return dates.map((date,index)=>{const pool=groups[index]||[],selected=[];for(const place of pool){if(used.has(place.id))continue;if(selected.length>=policy.maxDailyActivities)break;const religiousCount=selected.filter(isReligious).length;if(isReligious(place)&&!policy.religiousPrimary&&religiousCount>=1)continue;if(selected.length&&selected.at(-1).category===place.category&&selected.length>1&&selected.at(-2).category===place.category)continue;selected.push(place);used.add(place.id)}const start=requirements.dayConstraints?.find(c=>c.dayNumber===index+1&&c.type==='EARLIEST_START')?.value||policy.earliestStartTime,end=policy.latestEndTime;return{dayNumber:index+1,date,title:selected[0]?.zone||`Day ${index+1}`,dayType:'full',startTime:start<policy.earliestStartTime?policy.earliestStartTime:start,endTime:end,items:selected.map((place,itemIndex)=>({placeId:place.id,name:place.name,category:place.category,estimatedDuration:Number(place.duration||60),openingHoursStatus:place.openingHours?'REFERENCE':'REQUIRES_LIVE_CHECK',travelFromPrevious:{mode:itemIndex?'transit':'start',minutes:itemIndex?Math.max(10,Math.round(km(selected[itemIndex-1],place)*6)):0,walkingKm:itemIndex?Math.min(.6,km(selected[itemIndex-1],place)):0,fare:0}}))}})}
  function validate(plan,requirements,policy){const errors=[];if(plan.days.length!==plan.tripDays)errors.push({code:'DAY_COUNT_MISMATCH'});for(const day of plan.days){if(!day.items.length)errors.push({code:'EMPTY_DAY',dayNumber:day.dayNumber});if(day.dayType==='full'&&day.items.length<policy.minDailyActivities)errors.push({code:'THIN_FULL_DAY',dayNumber:day.dayNumber});if(day.items.length>policy.maxDailyActivities)errors.push({code:'DAILY_ACTIVITY_CAP',dayNumber:day.dayNumber});const main=day.items.filter(item=>!isMeal(item)&&!isRest(item));if(main.length>policy.maxMainAttractions)errors.push({code:'MAIN_ATTRACTION_CAP',dayNumber:day.dayNumber});if(day.endTime>policy.latestEndTime)errors.push({code:'LATE_END',dayNumber:day.dayNumber});const walkingKm=day.items.reduce((sum,item)=>sum+Number(item.travelFromPrevious?.walkingKm||0),0);if(walkingKm>policy.maxWalkingKm)errors.push({code:'WALKING_CAP',dayNumber:day.dayNumber});if(day.items.some(item=>item.openingHoursStatus==='CLOSED'))errors.push({code:'CLOSED_PLACE',dayNumber:day.dayNumber});let run=1;for(let i=1;i<day.items.length;i++){run=day.items[i].category===day.items[i-1].category?run+1:1;if(run>policy.maxConsecutiveCategory)errors.push({code:'CATEGORY_REPETITION',dayNumber:day.dayNumber})}}const all=plan.days.flatMap(day=>day.items),ratio=all.length?all.filter(isReligious).length/all.length:0;if(ratio>policy.maxReligiousRatio)errors.push({code:'RELIGIOUS_RATIO'});return{valid:errors.length===0,errors,metrics:{religiousRatio:ratio,dailyActivities:plan.days.map(day=>day.items.length)}}}
  function repair(plan,requirements,policy){const repaired=structuredClone(plan);for(const day of repaired.days){day.items=day.items.slice(0,policy.maxDailyActivities);let run=1;day.items=day.items.filter((item,index,array)=>{if(index===0)return true;run=item.category===array[index-1].category?run+1:1;return run<=policy.maxConsecutiveCategory});day.endTime=day.endTime>policy.latestEndTime?policy.latestEndTime:day.endTime}return repaired}
  function trace(requirements,plan,entities){const all=plan.days.flatMap(day=>day.items),ids=new Set(all.map(item=>item.placeId));return entities.map(req=>{if(req.clarification)return{...req,status:'NEEDS_CLARIFICATION',evidence:[req.clarification]};if(req.resolvedPlaceId)return{...req,status:ids.has(req.resolvedPlaceId)?'SATISFIED':'UNSATISFIED',evidence:[ids.has(req.resolvedPlaceId)?`${req.resolvedPlaceId} 已排入`:`${req.resolvedPlaceId} 未排入`]};return{...req,status:req.priority==='MUST'?'NEEDS_CLARIFICATION':'PARTIALLY_SATISFIED',evidence:['尚未解析為唯一地點或可驗證項目']}})}
  function run({requirements,places,dates}){const policy=Policy.resolve(requirements),selection=selectCandidates(requirements,places),groups=group(selection.candidates,dates.length,policy.minDailyActivities);let itinerary={tripDays:dates.length,days:schedule(requirements,dates,groups,selection.entities,policy)},validation=validate(itinerary,requirements,policy),repairApplied=false;if(!validation.valid){itinerary=repair(itinerary,requirements,policy);repairApplied=true;validation=validate(itinerary,requirements,policy)}const traceability=trace(requirements,itinerary,selection.entities),blocking=traceability.some(req=>req.priority==='MUST'&&req.status!=='SATISFIED');return{ok:validation.valid&&!blocking,itinerary,validation,repairApplied,traceability,policy,stages:['Candidate Place Selection','Grouping','Scheduling','Validation',...(repairApplied?['Repair']:[]),'Traceability']}}
  return{resolveEntities,selectCandidates,group,schedule,validate,repair,trace,run};
});
