(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;else root.PlanningPolicy=api})(typeof globalThis!=='undefined'?globalThis:this,function(){
  const BASE=Object.freeze({minDailyActivities:2,maxDailyActivities:5,maxMainAttractions:4,latestEndTime:'22:00',earliestStartTime:'08:00',maxWalkingKm:10,maxReligiousRatio:.5,maxConsecutiveCategory:2,restIntervalMinutes:150,bufferMinutes:20,maxUnrequestedDurationMinutes:240,maxUnrequestedAdmissionJPY:7000});
  const LEISURELY=Object.freeze({...BASE,maxDailyActivities:4,maxMainAttractions:3,latestEndTime:'21:00',earliestStartTime:'09:00',maxWalkingKm:7,restIntervalMinutes:120,bufferMinutes:35});
  const INTENSIVE=Object.freeze({...BASE,maxDailyActivities:6,maxMainAttractions:5,maxWalkingKm:14,restIntervalMinutes:180,bufferMinutes:15});
  const CHILD=Object.freeze({...BASE,maxDailyActivities:4,maxMainAttractions:3,latestEndTime:'20:30',earliestStartTime:'09:00',maxWalkingKm:7,restIntervalMinutes:105,bufferMinutes:30});
  const SENIOR=Object.freeze({...BASE,minDailyActivities:2,maxDailyActivities:4,maxMainAttractions:3,latestEndTime:'20:30',earliestStartTime:'09:00',maxWalkingKm:5,maxReligiousRatio:.3,maxConsecutiveCategory:2,restIntervalMinutes:105,bufferMinutes:35});
  function resolve(requirements={}){const senior=Boolean(requirements.mobilityProfile?.seniorPresent||requirements.specialNeeds?.includes('SENIOR_FRIENDLY')||(requirements.travelers?.seniors||[]).length),child=Boolean((requirements.travelers?.children||[]).length),pace=String(requirements.pace||'BALANCED').toUpperCase(),pacePolicy=pace==='LEISURELY'?LEISURELY:pace==='INTENSIVE'?INTENSIVE:BASE,profilePolicy=senior?SENIOR:child?CHILD:pacePolicy,religiousPrimary=Boolean(requirements.religiousSitePreference?.primaryInterest||requirements.collectionGoals?.length),profile=senior?'SENIOR':child?'CHILD':pace==='LEISURELY'?'LEISURELY':pace==='INTENSIVE'?'INTENSIVE':'STANDARD';return Object.freeze({...profilePolicy,maxReligiousRatio:religiousPrimary?1:profilePolicy.maxReligiousRatio,profile,religiousPrimary})}
  return{BASE,LEISURELY,INTENSIVE,CHILD,SENIOR,resolve};
});
